### ISSUE TITLE
[Bug]: FUD14

### ISSUE THREAD

**Issue by Chrisego2** [Jey-Cee/ioBroker.enocean#109]
### Contact Details

chrise.goldbrunner@web.de

### What happened?

A bug happened!
FUD14 dimmen über CMD set level funktioniert nach Update von 0.3.6 auf Version 0.6.0 nicht mehr. 

### Adapter Version

0.6.0

### JS-Controller Version

3.3.20

### Node JS Version

v14.18.1 

### NPM Version

6.14.15

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Bitte debug log anfügen,

**Comment by Chrisego2** [comment]
19.12.21 - Aktualisierung von 0.5.1 auf 0.6.0 -> on, off Befehle funktioniert, Set level nicht.

**Comment by Jey-Cee** [comment]
Da war eine Lücke in den Commands, die wurde geschlossen und jetzt ist Set level 2 statt 3.

**Comment by Chrisego2** [comment]
Danke. 
Mit Änderung der Datenpunkte von 3 auf 2 klappt wieder alles.
Gab es hier noch mehr Änderungen? 4: Teach-in; 5: Teach-in FSUD?

**Comment by Jey-Cee** [comment]
Es sind alle Befehle um eins runtergerutscht ab 3.
