### ISSUE TITLE
Meldung dass hier wohl die falsche node.js-Version installiert sei

### ISSUE THREAD

**Issue by guergen1** [Jey-Cee/ioBroker.enocean#110]
### Contact Details

guergen1@gmx.de

### What happened?

Bekomme beim Systemneustart eine Warnmeldung, Geräte laufen aber soweit!

### Adapter Version

0.5.4

### JS-Controller Version

3.3.22

### Node JS Version

14.18.2

### NPM Version

6.14.15

### Operating System

Debian

### Relevant log output

```shell
`warn | adapter "enocean" seems to be installed for a different version of Node.js. Trying to rebuild it... 2 attempt`
```

**Comment by Jey-Cee** [comment]
Du hast nodejs geupdated, richtig? Die Meldung kommt nicht vom Adapter sondern vom js-controller. Der versucht den Adapter neu zu Kompilieren, damit er auch richtig funktioniert. 
Sollte alles Laufen und keine weiteren Meldungen kommen ist alles in Ordnung.

**Comment by guergen1** [comment]
Das Update ist schon etwa sher, aber wenn alles ok ist, passt es ja!.
Weitere Meldungen kommen nicht

**Comment by Jey-Cee** [comment]
Der Automatische rebuild für den Adapter funktioniert nicht. 
Die (einfachste) Lösung ist es den Adapter neu zu installieren. 
1. Objekte vom EnOcean Adapter im Objekte Tab Exportieren
2. Adapter Löschen
3. Adapter installieren
4. Objekte importieren

**Comment by guergen1** [comment]
Ich gehe davon aus, dass ich die Geräte nach dem einspielen der Objekte nicht neu einlernen muss?

**Comment by Jey-Cee** [comment]
> Ich gehe davon aus, dass ich die Geräte nach dem einspielen der Objekte nicht neu einlernen muss?

Richtig deswegen vorher die Objekte exportieren.

**Comment by Jaaannis** [comment]
> Der Automatische rebuild für den Adapter funktioniert nicht. Die (einfachste) Lösung ist es den Adapter neu zu installieren.
> 
>     1. Objekte vom EnOcean Adapter im Objekte Tab Exportieren
> 
>     2. Adapter Löschen
> 
>     3. Adapter installieren
> 
>     4. Objekte importieren

Hi !
diesen Weg habe ich eingeschlagen, leider komme ich aus den restart loops nicht wieder heraus.

```
2022-01-15 17:37:14.806  - error: enocean.0 (20517) timeoutQueue is not defined
--
2022-01-15 17:37:14.855  - error:  enocean.0 (20517) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-01-15 17:37:14.855  - error: enocean.0 (20517) unhandled promise rejection: timeoutQueue is not defined
2022-01-15 17:37:14.856  - error: enocean.0 (20517) ReferenceError: timeoutQueue is not defined
```

ich habe diverse Versionen des Adapters versucht (vorher lief 6.0 stable), wenn man den falschen Serial port wählt geht gar nichts mehr. Jemand eine Idee?

**Comment by Jey-Cee** [comment]
Installier nochmal von Github.

**Comment by Jaaannis** [comment]
Ich kann den serial port wieder auswählen, restart loop ist weg.
Vielen Dank !

Einziger unterschied:

```
enocean.0 | 2022-01-16 08:58:13.645 | warn | The data length for a 4BS telegram is incorrect. The length is 0
```
erscheint jetzt regelmäßig, aber es scheint alles zu funktionieren.
