### ISSUE TITLE
FTKE state switch (null)

### ISSUE THREAD

**Issue by LosFoppos** [Jey-Cee/ioBroker.enocean#111]
### What happened?

Signal Strength ändert sich bei jedem druck, switch state bleibt allerdings (null). Adapter wurde bereits neu installiert etc. 

Läuft auf einem PI (im Slave)

### Adapter Version

0.6.0

### JS-Controller Version

3.3.22

### Node JS Version

12.22.6

### NPM Version

6.14.15

### Operating System

Ubuntu

**Comment by Jey-Cee** [comment]
Kannst du mir bitte das Log zur Verfügung stellen. Das Loglevel der Instanz muss dazu auf debug stehen.

**Comment by LosFoppos** [comment]
enocean.0
05.01.2022 14:11 debug Message for ID fee5f070 has been received. It was
repeated 0 times.

enocean.0
05.01.2022 14:11 debug 55000a0701eb300c46a7effee5f0700000ffffffff4d00

enocean.0
05.01.2022 14:11 debug Message for ID fee5f070 has been received. It was
repeated 0 times.

enocean.0
05.01.2022 14:11 debug 55000a0701eb3009099b0efee5f0700000ffffffff4f00

enocean.0
05.01.2022 14:10 debug Message for ID fee5f070 has been received. It was
repeated 0 times.

enocean.0
05.01.2022 14:10 debug 55000a0701eb300c09025afee5f0700000ffffffff4c00

enocean.0
05.01.2022 14:10 debug Message for ID fee5f070 has been received. It was
repeated 0 times.

enocean.0
05.01.2022 14:10 debug 55000a0701eb30067909e9fee5f0700000ffffffff4f00

enocean.0
05.01.2022 14:10 debug Message for ID fee5f070 has been received. It was
repeated 0 times.

enocean.0
05.01.2022 14:10 debug 55000a0701eb30000d8cf8fee5f0700000ffffffff4c00

enocean.0
05.01.2022 14:10 debug Message for ID fee5f070 has been received. It was
repeated 0 times.

enocean.0
05.01.2022 14:10 debug 55000a0701eb30015f422ffee5f0700000ffffffff4d00

enocean.0
05.01.2022 14:10 debug Message for ID fee5f070 has been received. It was
repeated 0 times.

enocean.0
05.01.2022 14:10 debug 55000a0701eb30040d40b0fee5f0700000ffffffff4d00

enocean.0
05.01.2022 14:10 debug Message for ID fee5f070 has been received. It was
repeated 0 times.

enocean.0
05.01.2022 14:10 debug 55000a0701eb300c2f731afee5f0700000ffffffff4c00

enocean.0
05.01.2022 14:10 debug Message for ID fee5f070 has been received. It was
repeated 0 times.

enocean.0
05.01.2022 14:10 debug 55000a0701eb3002ebc456fee5f0700000ffffffff4a00

enocean.0
05.01.2022 14:10 debug Message for ID fee5f070 has been received. It was
repeated 0 times.

enocean.0
05.01.2022 14:10 debug 55000a0701eb300259c564fee5f0700000ffffffff4c00

enocean.0
05.01.2022 14:09 info {"BaseID":"fffc2300","Frequency":"868.3
Mhz","Protocol":"ERP1","AppVersion":"2.15.0.0","ApiVersion":"2.6.9.0","ChipID":"059af846","ChipVersion":"454f0103","AppDescription":"GATEWAYCTRL"}

enocean.0
05.01.2022 14:09 debug Sent data: 5500010006790612

enocean.0
05.01.2022 14:09 debug Sent data: 5500010005700838

enocean.0
05.01.2022 14:09 debug Sent data: 55000100057025fb

enocean.0
05.01.2022 14:09 debug Sent data: 5500010005700a36

enocean.0
05.01.2022 14:09 debug Sent data: 5500010005700309

enocean.0
05.01.2022 14:09 info starting. Version 0.6.0 in
/opt/iobroker/node_modules/iobroker.enocean, node: v12.22.6, js-controller:
3.3.22

enocean.0
05.01.2022 14:09 debug statesDB connected

enocean.0
05.01.2022 14:09 debug States connected to redis: 192.168.178.95:9000

enocean.0
05.01.2022 14:09 debug States create User PubSub Client

enocean.0
05.01.2022 14:09 debug States create System PubSub Client

enocean.0
05.01.2022 14:09 debug Redis States: Use Redis connection:
192.168.178.95:9000

enocean.0
05.01.2022 14:09 debug objectDB connected

enocean.0
05.01.2022 14:09 debug Objects connected to redis: 192.168.178.95:9001

enocean.0
05.01.2022 14:09 debug Objects client initialize lua scripts

enocean.0
05.01.2022 14:09 debug Objects create User PubSub Client

**Comment by LosFoppos** [comment]
Danke für deine schnelle Antwort. Reicht dir das so?

Am Mi., 5. Jan. 2022 um 14:21 Uhr schrieb Steffen Foppe <
***@***.***>:

**Comment by Jey-Cee** [comment]
Hi, 
also ich konnte mir das jetzt anschauen und die Lösung ist einfach. Du hast die Verschlüsselung für den FTKE eingeschalten, das kann der Adapter aber nicht. Wenn du die deaktivierst funktioniert es.

**Comment by LosFoppos** [comment]
Oh ja, die Lösung war wirklich einfach. Besten Dank!
