### ISSUE TITLE
Request for Eltako FRWB (aka TF-RWB)

### ISSUE THREAD

**Issue by JustJoe21** [Jey-Cee/ioBroker.enocean#112]
**Manufacturer**: Eltako
**Model**: FRWB (aka TF-RWB)
**Production date/period**: ?
**Link to product**: https://www.eltako.com/fileadmin/downloads/de/_bedienung/TF-RWB_30000515-1_dt.pdf 
In contrast to the already added FRW, this model also has a temperatur sensor build in!

**Comment by Jey-Cee** [comment]
In version 0.6.3
