### ISSUE TITLE
Eltako TF100L-230V wrong EEP?

### ISSUE THREAD

**Issue by JustJoe21** [Jey-Cee/ioBroker.enocean#127]
Hi!

I'm still struggeling with getting an Eltako TF100L-230V Switch Actor working. Teach in (with a fully reset device) works fine so far but the device cannot be controlled by status changes from iobroker. I have another TF100L in use with a different base (Minisafe) and I compared the telegrams sent when switching the device from iobroker and from Minisafe:

One TF100L device teached into Minisafe has the ID 50a2313. The telegrams for ON/OFF look like this:

    55000707017af650050a23133100ffffffff5c00
    55000707017af670050a23133000ffffffff5e00

The other TF100L teached into iobrokder has the ID 0588125c and then I change the state of the device in the object tree (on/off) these telegrams are sent by iobroker:

    55000a0701eba501000009fff8260100000588125cff007b
    55000a0701eba501000008fff8260100000588125cff00ef 

Of course base ID and offset are different but the entire telegram looks totally different in regards to the switch command. This makes me think that maybe the registered EEPs in iobroker are not correct.

Maybe you have an idea?

**Comment by Jey-Cee** [comment]
Hi JustJoe21,

could be that the teachin wasnt succesfull. You can send the teachin telegram manual after adding the device to ioBroker.
I don't know now which one you have to send so try both of them.

It is funny to see that Eltako does use a generic switch telegram for the device, while they have a complete different one in their documents shown.

**Comment by JustJoe21** [comment]
Hi Jey-Cee,

thanks a lot! I used the teach in from your adpater's UI. How do I send a teach in manually and what you mean by "I don't know now which one you have to send so try both of them."? I suppose the teachin has worked since the device confirmed teach in with off/on sequence.

Thanks a lot for your help!

**Comment by Jey-Cee** [comment]
You will find them at the CMD object.
If the teachin was successfull i have no idea what could be the problem.

**Comment by JustJoe21** [comment]
That actually did the trick! Thanks a lot. I had to send the other teach-in telegram as well. After that, it worked and now the device can be controlled as expected.

The only thing that seems strange to me is that according to the Elataco manual https://www.eltako.com/fileadmin/downloads/de/_bedienung/TF100L-230V_30100012-5_dt.pdf that if the teach in telegram 0xE0400D80 is used, it should quit the tech in mode automatically after successfull teach in. However, this did not happen in my case.

Since the manul says that tech in mode can be quit using a special click pattern: "Lernmodus sofort sperren: Einen bereits eingelernten Funktaster (nicht Zentralsteuertaster) 3-mal kurz  plus 1-mal lang (>1 Sekunde) tippen.  Mit einem 2-maligen kurzen Ein- und Ausschalten der Last wird das Sperren signalisiert."

I suppose that this will not work with the iobroker adapter since it is teached in like a "Zentralsteuertaster" or "Base" but not as a single switch actor. Is there a known way to make Eltako devices quit teach in mode by sending a special telegram as well?

Thanks a lot for your help and your excellent adpater! I sent you a donation via PayPal.

Best regards,

   JustJoe

**Comment by Jey-Cee** [comment]
` Is there a known way to make Eltako devices quit teach in mode by sending a special telegram as well?`

@JustJoe21   no i do not know a telegram for this case. 
The adapter is always (if it is possible) teached in as a base.

Thanks for your donation.
