### ISSUE TITLE
Reason why adaptor cannot be installed via gui and latest has not been set to the lastest

### ISSUE THREAD

**Issue by HarterHorst** [Jey-Cee/ioBroker.enocean#128]
### What happened?

Is there a specific reason why the EnOcean Adapter cannot be installed via the gui? It's no showing up. From the changelog I can see version 0.6.4 ist the latest, but latest points to 0.5.4. 

Jusk asking, no offence. Mostly we all have better things to than maintaining github.

regards,
Horst

### Adapter Version

0.6.4

### JS-Controller Version

3.3.15

### Node JS Version

v12.22.4

### NPM Version

6.14.14

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Hi Horst, 
it is quite simple, in my mind the adapter is not ready for the official repository. 
Actual i have per week one or more requests for new devices to support, this means i have to update a stable version every second month or more. 
The other thing is that the device managment now is not that what i wanna have. We started to develop a global device managment which makes it way easier and more uniform for all adapter.
Thats a big step forward to release thru official repository.

Greets
Jey Cee
