### ISSUE TITLE
Eurotronic Stella E

### ISSUE THREAD

**Issue by ioBroker-User** [Jey-Cee/ioBroker.enocean#129]
**Manufacturer:** Eurotronic 
 **Model:** Stella E 
 **Production date/period:** 01.01.2018 
 **Link to product:** https://www.wibutler.com/media/downloads/56c4245154424fd8128b4804/Bedienungsanleitung_Stella-E.pdf 
 EEP A5 20-01

**Comment by Jey-Cee** [comment]
In version 0.6.5
