### ISSUE TITLE
Upgrade to Serialport 6.0.4

### ISSUE THREAD

**Issue by Apollon77** [Jey-Cee/ioBroker.enocean#13]
Hi,

in general Serialport 6 is much more stable then the older versions and in general (also when they moved to stream stuff) the old way is still supported.

The changes to the adapter are rather small (see https://github.com/Apollon77/iobroker.enocean/commit/d136bc7e9cd5de4eb6fd228fe495762fa708921d) ... but on Serialport page they wrote that "custom parser may need to be changed" ... and I saw that the adapter uses an custom parser ...
That's why I did not provided the PR for this :-)

You may want to check this ...

**Comment by Schluesselmeister** [comment]
Hi,
I am working on it. Changed the serialport to version 6 and I am testing the version in my system.
Additionally I have rewritten the parser.
I assume that I can upload the version latest at the weekend.

**Comment by Apollon77** [comment]
Cool!! Then we have soon all adapters on serialport 6.0.4 :-) Thank you!

**Comment by Schluesselmeister** [comment]
Added serialport 6 support.
