### ISSUE TITLE
Tipp-Funk-Jalousieaktor TF-TA55J

### ISSUE THREAD

**Issue by mustangix** [Jey-Cee/ioBroker.enocean#13]
**Manufacturer**:Eltako
**Model**:TF-TA55J
**Production date/period**:12/19
**Link to product**:
[Tipp-Funk-Sensor-Telegramme_und_Ansteuertelegramme.pdf](https://github.com/Jey-Cee/ioBroker.enocean/files/5641614/Tipp-Funk-Sensor-Telegramme_und_Ansteuertelegramme.pdf)
[TF-TA55J_30200232-1_dtsch.pdf](https://github.com/Jey-Cee/ioBroker.enocean/files/5641616/TF-TA55J_30200232-1_dtsch.pdf)

**Comment by Jey-Cee** [comment]
It is in the next release.
