### ISSUE TITLE
[Bug]: TF61J-230 Teach in Fails (partially)

### ISSUE THREAD

**Issue by JustJoe21** [Jey-Cee/ioBroker.enocean#130]
### What happened?

Hi,

I reported an issue with an Eltako TF-200L actor a few days ago. Teach in did work, the status of the actor was shown correctly in the object tree but I was not able to control it using the CMD command. It turned out the teach in has failed and I had to manally send a teach in (there were 2 teach in commands and I had to send both!) to get it working.

Now, I have a TF61J that I tried to teach in. Interestingly, I had the same issue here: I was able to use the teach process of the adpater and the actor was successfully deteced and shows up in the object tree. I can see state changes when I locally control the actor (up/down button). However, setting the CMD does not work again (the actor does not react).

I tried to put the actor in teach in mode again and sent a teach in command manually using the CMD but this did not work. After 2 minutes, the actor closes the teach in mode and I still cannot control the actor using the CMD.

Any ideas what might have gone wrong here.

One thing to add: Before teaching the actor into iobroker, I teached it into an Eltako Minisafe Gateway (this allows me to easily activate the teach in mode on the actor and to send up/down command). Could this be a reason why teach in with iobroker fails? In other words, the actor may only be teached into one base? 

Thanks for your suggestions!

Joe

### Adapter Version

0.6.4

### JS-Controller Version

4.0.15

### Node JS Version

?

### NPM Version

?

### Operating System

Ubuntu

**Comment by JustJoe21** [comment]
Just one more thing: Adding a TF100L to the Eltako Minisafe Gateway AND to iobroker works just fine. However, the teach in using the adapter interface only adds the objects to the tree. I have to send Teachin (2) and Teachin (1) commands to add iobroker successfully. So I assume the TF61J should also work teached into both gateways at the same time but to me it looks like the teach in process of the adpater for Tipp Funk devices has issues.

**Comment by Jey-Cee** [comment]
Can you please  provide me a log in debug where i can see the teachin procedure. 
The thing with TippFunk devices is that they send a specific telegram to identify them. But this telegram depends on the device and the manufacturing date.

**Comment by JustJoe21** [comment]
Sorry for the long delay. I tried some more but did not have success. Now, I tried using a TF-TA55J. The interesting thing is here that it shows exactly the same behaviour as with TF61J: I can successfully teach in the device, I get the status changes if these are triggered by the device (TF-TA55J has a built-in rocker) but for what ever reason, I cannot control the device from IO broker by changing the CMD value in the object tree. The log states that something is sent but the actor does not react.

Here are my logs for TF-TA55J:

Teach-In (which is successfull!):
enocean.0
2022-05-09 22:50:46.363	debug	55000a0701eba5fff80d80fff8260e81000584ab8c5c00

enocean.0
2022-05-09 22:50:46.348	debug	Packet type 2 received: {"code":"OK"}

enocean.0
2022-05-09 22:50:46.348	debug	55000100026500

enocean.0
2022-05-09 22:50:46.347	debug	Packet type 2 received: {"code":"OK"}

enocean.0
2022-05-09 22:50:46.347	debug	55000100026500

enocean.0
2022-05-09 22:50:46.329	debug	Sent data: 55000a0701eba5fff80d80fff8260e00010584ab8cff007f

enocean.0
2022-05-09 22:50:46.326	debug	Sent data: 55000a0701eba5fff80d80fff8260e00010584ab8cff007f

enocean.0
2022-05-09 22:50:41.511	info	Create objects for F6-02-02 from ELTAKO with id: 0584ab8c

enocean.0
2022-05-09 22:50:41.327	info	Create objects for TF-01-01 from ELTAKO with id: 0584ab8c

enocean.0
2022-05-09 22:50:41.325	info	Eltako TF-TAx5J detected

enocean.0
2022-05-09 22:50:41.319	debug	teachinMethod: D1 from ID "0584ab8c"

enocean.0
2022-05-09 22:50:41.309	debug	55000d0701fdd100d0ff000003f20584ab8c0100ffffffff5c00


Pressing a button on the rocker of the device:

enocean.0
2022-05-09 22:53:16.462	debug	Message for ID 0584ab8c has been received. It was repeated 1 times.

enocean.0
2022-05-09 22:53:16.460	debug	55000707017af6010584ab8c3100ffffffff5c00


Changing the CMD value (no effect):

enocean.0
2022-05-09 22:52:21.161	debug	55000a0701eba500000108fff8260481000584ab8c5c00

enocean.0
2022-05-09 22:52:21.130	debug	Packet type 2 received: {"code":"OK"}

enocean.0
2022-05-09 22:52:21.129	debug	55000100026500

enocean.0
2022-05-09 22:52:21.116	debug	Sent data: 55000a0701eba500000108fff8260400000584ab8cff0015

enocean.0
2022-05-09 22:52:21.096	debug	state 0584ab8c.CMD changed: 1 (ack = false) state: {"val":1,"ack":false,"ts":1652129541093,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1652129541093}

What could be wrong here? It is really strange that all Eltako actors I tried so far were able to teach in without any issues but controlling did not work. In case of the TF100L-230 I had to do another manual teach-in with a different EEP which then worked (I was then able to control the deivce) but the blind actors do not work at all.

Do you have any idea what could be wrong here? I found very old postings in other forums of people reporting that they got TF-TA55J working with older versions of the Enocean adapter.

**Comment by Jey-Cee** [comment]
Sorry for the Delay. Did you manage to get the actuators to work?
Looks like you did not have set the running time, whitout it is 0 seconds and they will not switch the output on.

**Comment by JustJoe21** [comment]
Thanks for your reply. No, I did not get it working. 

You mean, the RT needs to be set? The value was already set to 80 100ms. But anyway, changing this value and then commiting a change to CMD value does not show any reaction of the actor. What exactly should I change in your optinion?

**Comment by Jey-Cee** [comment]
Ok if it was set, i will have a look if there is a problem with the profile.

**Comment by JustJoe21** [comment]
Hi! That would be great! I would really love to get this device working. If required, I can lend you a device for testing purposes. 

Thanks for your help!

**Comment by JustJoe21** [comment]
Any news about this issue? As stated before, I can lend you a device for testing if that helps to fix the problem... Thx!

**Comment by Jey-Cee** [comment]
Hi no news, i missed that you can send me one. Please send it to Christoph Gerle, Schwabenstraße 40, 87668 Rieden
