### ISSUE TITLE
Funk-Fenstersensor senso secure

### ISSUE THREAD

**Issue by Tomek5111** [Jey-Cee/ioBroker.enocean#131]
**Manufacturer**: Siegenia
**Model**: senso secure
**Production date/period**: 
**Link to product**: https://shop.siegenia.com/siegenia/de/Smarthome-Root/Smart-Home/Funk-Fenstersensor-senso-secure/p/GSEF0100-0D4010

Funkstandard: enOcean (868,3MHz)
enOcean equipment profile (eep): D2-06-50
Schutzart: Elektronik: IP64, Batteriefach IP 40
Batterien: 2 x AAAA
Lebensdauer der Batterien: ca. 3 Jahre

**Comment by Jey-Cee** [comment]
In next version
