### ISSUE TITLE
[Bug]: Can not connect to host: TypeError: Cannot read property 'pipe' of null

### ISSUE THREAD

**Issue by matty67** [Jey-Cee/ioBroker.enocean#135]
### What happened?

The issue occures, when using TCP Connection.

Can not connect to host: TypeError: Cannot read property 'pipe' of null

### Adapter Version

 0.6.4

### JS-Controller Version

3.3.21

### Node JS Version

12.22.11

### NPM Version

6.14.16

### Operating System

Debian

### Relevant log output

```shell
2022-03-31 11:33:24.090	warn	Can not connect to host: TypeError: Cannot read property 'pipe' of null

enocean.0
2022-03-31 11:33:23.936	info	starting. Version 0.6.4 in /opt/iobroker/node_modules/iobroker.enocean, node: v12.22.11, js-controller: 3.3.21
host.iobroker_2
2022-03-31 11:33:23.496	info	instance system.adapter.enocean.0 started with pid 18848
```

### Anything else?

In main.js in method connectTCP the variable SERIAL_PORT is undefined.
It should be tcpClient.

**Comment by Jey-Cee** [comment]
Did you install from Github?

**Comment by matty67** [comment]
Yes, as userdefined adapter from URL https://github.com/Jey-Cee/ioBroker.enocean.git

**Comment by Jey-Cee** [comment]
Install from npm, the version on Github is broken.
You are right with tcpClient.

**Comment by matty67** [comment]
Ok. Thank you, from NPM works. Fine.
