### ISSUE TITLE
[Bug]: Eltako FFKB uses not needed Sender ID

### ISSUE THREAD

**Issue by cdaerr** [Jey-Cee/ioBroker.enocean#136]
### What happened?

When a Eltako FFKB is added, a Sender ID is generated, but it is not needed because this device does not receive anything. When using this device for Window open and tilt detection of 20 Windows much Sender IDs are used. 

Could I run in a Limitation with this behavoir?

### Adapter Version

v0.6.4

### JS-Controller Version

4.0.15

### Node JS Version

v14.19.1

### NPM Version

6.14.16

### Operating System

Ubuntu

### Anything else?

![grafik](https://user-images.githubusercontent.com/98185044/161418236-87710150-8942-46f4-b764-63ef2ad9cfa4.png)

**Comment by cdaerr** [comment]
Same behavior for FTKB. It it the same sensor but with Solar Supply.

**Comment by Jey-Cee** [comment]
Can't confirm this.

**Comment by cdaerr** [comment]
I also tried reinstall Adapter, delete the device and add new. Same result.

Please try to fix.
