### ISSUE TITLE
[Bug/Question]: FSB14 Rollo fährt mit Command UP und DOWN immer nur die in der RunningTime eingetragene Zeit hoch und runter

### ISSUE THREAD

**Issue by imp3r4t0r** [Jey-Cee/ioBroker.enocean#139]
### Contact Details

git@hst-it.de

### What happened?

Hallo Jey-Cee,

ich habe seit geraumer Zeit das Problem, dass meine Rollos (FSB14), wenn in der RunningTime RT ein Wert drin steht (z.B. 2s), dass er dann auch nur 2s hoch bzw. runterfährt, wenn ich den Command UP (1) oder DOWN (2) triggere. Wahrscheinlich ist das so auch gewollt!? Ich habe damit allerdings das Problem, dass die RT jedes mal neu gesetzt wird, wenn ich entweder mit dem Wandschalter den Rollo starte und dann z.B. nach 2s durch erneutes Drücken anhalte (die RT wird dann auf 2s gesetzt) oder wenn ich dasselbe über ioBroker mit z.B. einem UP Command und nach 2s mit einem STOP Command anhalte. Ab dann kann ich mit einem erneuten UP bzw. DOWN Command den Rollo nur noch jeweils 2s lang bewegen, außer ich setze die RT manuell vorher auf 0s, dann fährt er ganz hoch oder ganz runter.

Die eigentliche Idee der RT ist wahrscheinlich, dass man nur hierüber eventuelle "Zwischenstufen" ermitteln und schalten könnte, oder? Müsste es dafür dann aber nicht ein RT_Gesamt Attribut o.Ä. geben, wo man die Gesamtdauer von ganz oben bis ganz unten einträgt (Default wahrscheinlich 0s) und der UP bzw. Down Command dann diese Zeit läuft? Bin irgendwie etwas ratlos, wie ich das sinnvoll lösen kann (außer eben händisch vor jedem Command die RT noch auf 0s setzen) und würde mich über eine Anregung dazu freuen :-)

Das Verhalten tritt auch bei der neusten Version 0.7.0 auf, war aber auch bei der 0.6.4 schon so. Ich glaube bei ca. 0.3.x ging es noch.

Ein Beispiel meiner Rollo Konfiguration.
![Bildschirmfoto 2022-05-31 um 11 07 26](https://user-images.githubusercontent.com/150846/171137151-4d122d33-7fed-4143-8bde-2ca3d6d35268.png)

PS: Der FSB14 liefert ja leider meistens manchmal "Abschlusstelegram", wenn der Rollo dann ganz oben oder unten ist. Entsprechend werden dann auch die TOP, BOT, UP und DO Attribute nicht immer richtig gesetzt. Falls es Sinn machen würde irgendeine Art RT_Gesamt Attribut einzuführen, wäre es dann auch sinnvoll nach der abgelaufenen Zeit diese Werte dann trotzdem setzen zu lassen?

Ich sage vorab schon mal herzlichen Dank!
Holger

### Adapter Version

0.7.0

### JS-Controller Version

4.0.23

### Node JS Version

14.19.1

### NPM Version

6.14.17

### Operating System

Ubuntu

**Comment by Jey-Cee** [comment]
Hallo Holger, 
das steht schon auf der Todo Liste, #92.
Ich muss nur Aufpassen das ich hier nicht alle Laufenden Installationen damit Kaputt mache.
Das war übrigens schon immer so das es nur diesen einen Datenpunkt gibt in dem die Gefahrene Zeit und die zu fahrende Zeit  steht.
Meine Überlegung war RT in 2 neue, Travelled Time und Time to drive, auf zu Teilen und den alten Vorübergehend bestehen zu lassen.

**Comment by imp3r4t0r** [comment]
Alles klar, vielen Dank!
Ich hab bisher nur nach Infos im Zusammenhang mit dem FSB14 geschaut. Wenn du es eh irgendwo auf dem Schirm hast, dann ist es ja wunderbar :-) Ich behelfe mir dann zunächst mal damit die RT vorher irgendwie auf 0 zu setzen.
