### ISSUE TITLE
add nodon STP-2-1-05

### ISSUE THREAD

**Issue by Reeeves** [Jey-Cee/ioBroker.enocean#14]
**Manufacturer**: nodon
**Model**: STP-2-1-05
**Production date/period**: unbekannt
**Link to product**: https://nodon.fr/en/nodon/enocean-temperature-sensor/

Thank you!

**Comment by Jey-Cee** [comment]
Coming with the next version.

**Comment by Reeeves** [comment]
Hello Jey-Cee

Thank you for integrating this device. Nice!

Unfortunately the displayed temperature value is wrong...  58.2°C at -60dbm.

Log: 
 (30959) Message for ID 051c22bf has been received.
 (30959) 55000a0701eba500007408051c22bf0001ffffffff3c00

I have done a uninstall and new install of the adapter today.
Perhaps my sensor is broken... or can you give me an advice?

Thanks,
Reeves

**Comment by Jey-Cee** [comment]
@Reeeves i will check this
