### ISSUE TITLE
Kieback&Peter RBW322-FTL

### ISSUE THREAD

**Issue by KlausStoertebeker** [Jey-Cee/ioBroker.enocean#141]
**Manufacturer**: Kieback&Peter
**Model**: RBW322-FTL
**Production date/period**: 2015+
**Link to product**: https://www.manualslib.de/manual/478469/Kiebackandpeter-Rbw322-Ftl.html?page=5#manual

The RBW322-FTL uses EEP "[D2-10-01](http://tools.enocean-alliance.org/EEPViewer/profiles/D2/10/01/D2-10-01.pdf)" and I would send you a device for developing.

**Comment by Jey-Cee** [comment]
Please send me an email jey-cee@live.com

**Comment by Jey-Cee** [comment]
In next version.

**Comment by KlausStoertebeker** [comment]
Hi Jey-Cee,
your implementation of the RBW322-FTL works fine, but I have the problem that I can't set up the time programs :-( Although I use as trigger the change of the signal strength (as you suggested in your last private message) to make sure the commands are send after receiving a message from the panel it seems that nothing happens after sending the time program data in that the new time program set up doesn't show up in the panels display.
But the data for the time program seem to be acknowledged (if you hover with the mouse pointer over an object ID's value the acknowledge flag shows "true").

I hope you can tell me what's going wrong, therefore I have included my blockly script which does the time program setup and the corresponding log file for analyzing purposes:

[Blockly script](https://github.com/Jey-Cee/ioBroker.enocean/files/9499396/Wohnzimmer_Heizungszeitprogramm_einstellen-blockly.txt)
[log file](https://github.com/Jey-Cee/ioBroker.enocean/files/9499357/iobroker.2022-09-06.log)

Regards
"Klaus"

**Comment by Jey-Cee** [comment]
Sorry for the delay. 
It seems that you always send deletion telegrams, as you set TPD = 1, but missing to set it to 0 later in your Blockly.
