### ISSUE TITLE
Falsche Versionsanzeige nach update und downgrade

### ISSUE THREAD

**Issue by guergen1** [Jey-Cee/ioBroker.enocean#143]
### Contact Details

guergen1@gmx.de

### What happened?

Ich habe von der Version 0.5.4 auf die Version 0.7.1 ein Update über github gemacht. Leider war dann erstmal keine Funktion der Lampen möglich. Bin dann wieder zurück auf die Version 0.5.4 
Inhalt package-lock.json:
`{
  "name": "iobroker.enocean",
  "version": "0.5.4",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@alcalzone/release-script": {
      "version": "2.2.1",
      "resolved": "https://registry.npmjs.org/@alcalzone/release-script/-/release-script-2.2.1.tgz",
      "integrity": "sha512-kW0kRV154peNiPAY9ZjcaHtVjp/OKOyp6gVga9GSXIHjIxGcygHJ1CWVCb2HfvHzOxfbHPVIKemNOc568wU9xQ==",
      "dev": true,
      "requires": {
        "alcalzone-shared": "^4.0.0",
        "axios": "^0.21.1",
        "colors": "^1.4.0",
        "execa": "^5.1.1",
        "fs-extra": "^10.0.0",
        "semver": "^7.3.5",
        "yargs": "^17.0.1"
`
Allerdings wird mit im Admin (6.2.18) unter Instanzen weiterhin die 0.7.1 angezeigt:
![grafik](https://user-images.githubusercontent.com/34395245/187032067-27d304d7-a9ad-4bbf-b7cf-0b7fdfc566df.png)
Unter Adapter wird die korrekte Version angezeigt:
![grafik](https://user-images.githubusercontent.com/34395245/187032093-0dacfa6a-1426-484e-baf8-71a9b5200778.png)
Cache wurde gelöscht, bzw anstatt Firefox wurd Chome testweise benutzt.
Ein "iob list adapters" bringt mir ebenfalls ein "0.7.1" zurück

### Adapter Version

0.7.1

### JS-Controller Version

4.0.23

### Node JS Version

16.17.0

### NPM Version

8.15.0

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Das die Version der instanz von dem Installierten Adapter abweicht habe ich bisher nur in Mulstihost systemen gesehen. Da ist auf beiden Hosts der Adapter in Unterschiedlichen Versionen installiert gewesen.
Ist das ein Multihost System?

**Comment by guergen1** [comment]
Ja, das ist ein Multihostsystem. Bis vor ein paar Wochen war, warum auch immer, auf beiden Systemen die 0.5.4 drauf. Dann hab ich die unnötige Version auf dem Master gelöscht und heute auf dem Slave, wo der Adapter normal läuft, 0.7.1 Updaten wollen. Da es sogleich Probleme gab und ich leider nicht viel Zeit hatte, hab ich wieder die 0.5.4 installiert

**Comment by Jey-Cee** [comment]
Kannst du mir bitte mal das ganze Log von dem Tag, an dem du das Update gemacht hast, zu kommen lassen: jey-cee@live.de

**Comment by guergen1** [comment]
Das Update von 0.5.4 auf 0.7.0 habe ich vor zwei oder drei Wochen schonmal gemacht, da ist mir aufgefallen, dass ich die Leuchten nicht mehr steuern konnte. Hab das dann auch erst wieder Rückgängig gemacht um abzuwarten ob es evtl mit der nächsten Version wieder geht; ist aber leider nicht so. In den aktuellen Log´s steht nichts mehr drin.
Mit den Versionen 0.7.0 und 0.7.1 kann ich nichts mehr steuern; ist aber scheinbar ein anderes Thema.

**Comment by guergen1** [comment]
Mail ist als unzustellbar zurück gekommen

**Comment by guergen1** [comment]
[iobroker.2022-08-27.log.gz](https://github.com/Jey-Cee/ioBroker.enocean/files/9439464/iobroker.2022-08-27.log.gz)

**Comment by Jey-Cee** [comment]
`2022-08-27 21:55:46.358  - [31merror[39m: host.iob-slave States database error: connect ECONNREFUSED 192.168.1.201:9000
2022-08-27 21:55:46.816  - [31merror[39m: host.iob-slave Could not execute primary host determination: Error Unknown Script b0bd9e6fd92479ccf43654a7ba7443c915d0a742`

Das sieht nach Problemen mit deiner Multihost Umgebung aus. Kommt das öfter vor?


> da ist mir aufgefallen, dass ich die Leuchten nicht mehr steuern konnte.

Das ist logisch wenn die Instanz nicht auf dem Host ist an dem dein Stick Steckt, der Adapter kann dann ja auch nix senden.

**Comment by Jey-Cee** [comment]
Gibts hier was neues?

**Comment by guergen1** [comment]
Ist mittlerweile nicht mehr aufgetreten! Versionsanzeige auch im Multihostsystem ok!
