### ISSUE TITLE
Eltako FSB14 BOT und TOP Datenpunkte  stehen dauerhaft auf  "false"

### ISSUE THREAD

**Issue by Markus-3** [Jey-Cee/ioBroker.enocean#146]
Die Datenpunkte BOT und TOP werden bei Fahrbefehl Eingabe über den Datenpunkt CMD nicht aktualisiert. Dies geschieht nur bei Betätigung des Wandtasters.

![image](https://user-images.githubusercontent.com/85412355/192724121-f01367a4-cb42-4704-86e2-2762085a7e13.png)

### Adapter Version

0.8.2

### JS-Controller Version

4.0.23

### Node JS Version

16.17.1

### NPM Version

8.15.0

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Das kann ich nicht Nachvollziehen. 
Sicher das der Aktor so lange aktiv ist bis die am Aktor eingestellte Zeit abgelaufen ist? Erst danach wird das Telegram ausgelöst.
Da der Taster dem Aktor keine Fahrzeit mitteilt bleibt der Aktor Aktiv bis die eingestellte Zeit abgelaufen ist, daher wird der Status hier auch gemeldet.

**Comment by Markus-3** [comment]
Der wert im Feld TTT MUSS identisch mit der eingestellten Zeit am FSB14 sein damit BOT und TOP aktualisiert werden.

Die Info muss man aber echt irgendwo schriftlich niederschreiben. Da wäre ich selbst nie drauf gekommen.

**Comment by Jey-Cee** [comment]
Findet man in Zukunft in der Objektbeschreibung, so wie hier: https://github.com/Jey-Cee/ioBroker.enocean/blob/c91981b1c92707a89fc5217b7665238d8dd5f5fc/lib/definitions/eep/TF-13/TF-13-04.json#L43
