### ISSUE TITLE
Eltako FSB14 Eingaben in TTT oder RT mit , oder. werden nicht ausgeführt

### ISSUE THREAD

**Issue by Markus-3** [Jey-Cee/ioBroker.enocean#147]
### What happened?

Wird im FSB14 im Datenpunkt TTT eine Zahl mit Komma oder Punkt eingegeben wird der Befehl COMD nicht ausgeführt. Es muss eine Ganze Zahl sein!
1,1 oder 1.1 werden nicht ausgeführt, 1 hingegen schon. 

![image](https://user-images.githubusercontent.com/85412355/192811842-8a3af825-a3c3-4393-a47c-c698938161ce.png)

### Adapter Version

0.8.2

### JS-Controller Version

4.0.23

### Node JS Version

16.17.1

### NPM Version

8.15.0

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Javascript betrachtet das nicht als Zahl sondern als String, was dazu führt das es die Verarbeitung des Wertes im Adapter unmöglich macht, mit der Akutellen Logik.

**Comment by Markus-3** [comment]
Den Wert habe ich von Hand in den Adapter geschrieben. Zahlen mit Komma oder Punkt nimmt er nicht. Zahlen die ich aus dem Blockly ins TTT schreibe funktionieren ebenso wenn dieses ganze Zahlen sind. Ich Runde die Zahl gerade im Blockly auf den vollen Wert dann geht es, ist halt etwas ungenau aber besser als nichts.
In der Version 0.7.1 hat es auch ohne runden funktioniert

**Comment by Markus-3** [comment]
Problem besteht auch weiterhin in Version 0.8.3

**Comment by Jey-Cee** [comment]
Bitte von Github installieren und Testen.

**Comment by Markus-3** [comment]
Version 0.8.3 am 16.10.22 neu installiert. Sowohl Werte mit Komma als auch Punkt werden nun ausgeführt.
SPITZE!!!!

p.s. Sinnhafter weise sind die Fahrzeiten auf eine stelle nach dem Komma zu begrenzen/ zu runden wenn man diese (z.B. im Blockly) berechnet.
