### ISSUE TITLE
Easyfit Temperature & Humidity Sensor

### ISSUE THREAD

**Issue by Wahl-HHer** [Jey-Cee/ioBroker.enocean#155]
**Manufacturer**: Easyfit
**Model**: ETHS
**Production date/period**:
**Link to product**: https://www.easyfit-controls.com/de/portfolio/temperature-humidity-sensor-ethsu-oem/
[ETHSx_DataSheet_April2022.pdf](https://github.com/Jey-Cee/ioBroker.enocean/files/9909699/ETHSx_DataSheet_April2022.pdf)

**Comment by Jey-Cee** [comment]
In version 0.8.4
