### ISSUE TITLE
[Bug]: Adapter does not start any more

### ISSUE THREAD

**Issue by JustJoe21** [Jey-Cee/ioBroker.enocean#159]
### Contact Details

joachim@schwieren.de

### What happened?

After teaching in a TF-RWB and a TF-100A (which failed), the adapter does not start any more. Here are the errors I get from the log:

enocean.0 | 2022-12-23 13:46:57.987 | info | The TCP port was closed.
-- | -- | -- | --
enocean.0 | 2022-12-23 13:46:57.982 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
enocean.0 | 2022-12-23 13:46:57.981 | info | terminating
enocean.0 | 2022-12-23 13:46:57.980 | info | cleaned everything up...
enocean.0 | 2022-12-23 13:46:57.976 | error | Cannot read properties of undefined (reading 'objects')
enocean.0 | 2022-12-23 13:46:57.975 | error | TypeError: Cannot read properties of undefined (reading 'objects') at update.main (/opt/iobroker/node_modules/iobroker.enocean/lib/update.js:20:29)
enocean.0 | 2022-12-23 13:46:57.975 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'objects')
enocean.0 | 2022-12-23 13:46:57.974 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

How can I fix that? Any idea what causes the adapter not to start any more?

### Adapter Version

0.8.4

### JS-Controller Version

6.1.4

### Node JS Version

?

### NPM Version

?

### Operating System

Ubuntu

**Comment by JustJoe21** [comment]
Deleting the TF100A from the object tree fixed the issue. Looks like something is wrong with this device in the device definition.

**Comment by Jey-Cee** [comment]
Sorry for the delay. If have to fix this adapter side.
