### ISSUE TITLE
add Eltako FHF

### ISSUE THREAD

**Issue by rapacides** [Jey-Cee/ioBroker.enocean#16]
**Manufacturer**: Eltako
**Model**: FHF
**Production date/period**: unknown
**Link to product**: https://www.eltako.com/fileadmin/downloads/de/_bedienung/FHF_30000420-1_dt.pdf

Hi,
ich habe bereits ein bisschen versucht mein FHEM-Setup auf ioborker zu migrieren.
(Ich bin kein Programierer, agiere als mit gefährlichem Halbwissen :) )

In der devices.json habe ich den Part für den FHF Fenstergriff hinzugefügt:
`    "FHF": {
      "EEP": ["F6-10-00"],
      "autocreate": true,
      "teachin_method": "RPS",
      "id_offset": false,
      "help": {
        "de": {
          "1":"Auf 'Gerät Hinzufügen' klicken.",
          "2":"Teach-In starten."
        }
      }
    },`

Damit Funktioniert auch das einlernen, leider aber als F6-02-02 bzw. im Log erscheint "F6-03-xx detected and added to devices".
Wenn ich danach das angelegte Obejkt auf F6-10-00 abändere und die zwei Datenpunkte "WIN" und "WINT" anlege, bekomme ich beim öffnen bzw. kippen die richtigen Werte zurück gemeldet.

Ich hoffe diese Infos helfen beim hinzufügen ins Projekt.

Vielen Dank und tolle Arbeit.

**Comment by Jey-Cee** [comment]
in version 0.3.1
