### ISSUE TITLE
Enhancement: Update FUD61NPN-230V

### ISSUE THREAD

**Issue by f-io** [Jey-Cee/ioBroker.enocean#160]
**Eltako** **FUD61NPN-230V**
**[Link to product](https://www.eltako.com/de/product/professional-smart-home/funkaktoren-fur-die-dezentrale-gebaudefunk-installation/fud61npn-230v/)**

Hi,

the actual EEPs for FUD61NPN-230V (TF-13-07, TF-13-06) doesn't support to alter the "Last Dimm Value", maybe it is possible to enhance the profile to access this value?

Cheers,
Fio

**Comment by Jey-Cee** [comment]
Hi Fio,

it is not possible to alter the last dimm value, because that is not accessible. You can try to set the level while the dimmer is off, if you wish to change that value and turn the light on with it from a switch.
