### ISSUE TITLE
Kopp Free control switch 822X or shutter control 8080.02 missing

### ISSUE THREAD

**Issue by Markus-3** [Jey-Cee/ioBroker.enocean#162]
Kopp Free control 
switch 822X (8228.0202.0) page 6
Rolladen 8080.02 page 13
https://theunissen.com/media/downloads/free-control-comfort-technische-infos.pdf

Link 
https://www.kopp.eu/technische-informationen-zum-funk-system-free-control

**Comment by Jey-Cee** [comment]
I can not see any information that this devices are EnOcean compatible.

**Comment by Jey-Cee** [comment]
Closing this issue while it seems not related to EnOcean and there is no response.
