### ISSUE TITLE
ELTAKO FTR65HB (Temperatur-Regler)

### ISSUE THREAD

**Issue by tgoerlich** [Jey-Cee/ioBroker.enocean#17]
**Manufacturer**: ELTAKO
**Model**: FTR65HB
**Production date/period**:
**Link to product**: https://www.eltako.com/fileadmin/downloads/de/_bedienung/FTR65HB_30065480-1_dt.pdf

Betriebsart FHK: EEP: A5-10-06
Lerntelegramm: 0x40300D87
Datentelegramm:

    Data_byte0 = 0x0F
    Data_byte1 = Istttememperatur 0xFF..0x00 entspricht 0..40°C
    Data_byte2 = Solltemperatur 0x00..0xFF entspricht 0..40°C
    Einstellbarer Bereich: 12..28°C Frostsymbol = 8°C

Betriebsart TF61: EEP: A5-38-08
Lerntelegramm: 0xE0400D80
Datentelegramm:

    AUS = 0x01000008
    EIN = 0x01000009

Hysterese: 1°

**Comment by Jey-Cee** [comment]
In version 0.3.1
