### ISSUE TITLE
[Bug]: Fehlendes Verzeichnis /dev/serial/by-id führt zu Fehlermeldung

### ISSUE THREAD

**Issue by uklatt** [Jey-Cee/ioBroker.enocean#170]
### What happened?

Bei Version 0.9.0 innerhalb eines buanet Docker Containers und Nutzung über ser2net erscheint die o.g. Fehlermeldung.

Ich habe das Verzeichnis manuell erstellt. Dann erscheint die Meldung nicht mehr.

Tschau
Uwe

### Adapter Version

0.9.0

### JS-Controller Version

4.0.24

### Node JS Version

18.17.1

### NPM Version

9.6.7

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Danke fürs melden.
Welche Meldung meinst du? Ein Log oder Screenshot wäre hier gut.

**Comment by uklatt** [comment]
Wenn das Verzeichnis nicht existiert, kommt die Fehlermeldung bei jedem Start des Adapters.
In meiner Docker Konfiguration ist das Verzeichnis standardmäßig nicht vorhanden.
Ich musste es manuell anlegen, damit der Adapter nicht mehr "meckert".
Das tritt anscheinend auf, wenn keine USB devices vorhanden sind.
(Ich nutze nur ser2net für die Anbindung.)

Tschau
Uwe

**Comment by Holger-Will** [comment]
> kommt die Fehlermeldung bei jedem Start des Adapters.
was sagt die Fehlermeldung genau? 
Wäre super, wenn du das Verzeichnis nochmal löschen könntest, und dann einen Screenshot oder den Text aus den Logs hier posten könntest...

**Comment by uklatt** [comment]
Ich wollte heute das Verzeichnis testhalber entfernen und habe dabei festgestellt: Es ist nicht mehr da!
Keine Ahnung, ob der udev daemon das gelöscht hat.
Interessanterweise kommt die Fehlermeldung nun nicht mehr (auch ohne das Verzeichnis **/dev/serial/by-id**).
Sehr merkwürdig.

Tschau
Uwe

**Comment by Holger-Will** [comment]
Danke, dass Du das nochmal getestet hast/bzw. testen wolltest.

@Jey-Cee sollte das nicht mit dem [commit](https://github.com/Jey-Cee/ioBroker.enocean/commit/791cde8f99759642ef24a675d6d6c466a722ef45) erledigt sein?

**Comment by Jey-Cee** [comment]
@Holger-Will ich glaub du hast den falschen commit erwischt, es ist dieser hier: 9f3e4a40c854cdf14b6a193a4dedb7aa573168ad

**Comment by Holger-Will** [comment]
uups! ja richtig

**Comment by Holger-Will** [comment]
#181 beinhaltet einen fix: prüfen ob `/dev/serial/by-id` vorhanden ist bevor es gelesen wird... ich denke wir können dann auch den try catch block drum herum löschen...

**Comment by Holger-Will** [comment]
mit dem merge von heute, kann das geschlossen werden.
