### ISSUE TITLE
[Bug]: State SLSW für X1-01-02 ist read only

### ISSUE THREAD

**Issue by Holger-Will** [Jey-Cee/ioBroker.enocean#176]
### Contact Details

h.will@klimapartner.de

### What happened?

wenn man ein virtuelles Gerät mit EEP X1-01-02 (a5-10-06) anlegt, wird der State für den Tag/Nacht Schlater (SLSW) als read only angelegt.

in den object_definitions ist das auch so hinterlegt:
https://github.com/Jey-Cee/ioBroker.enocean/blob/91164aabe92ed9c55d607b347227eb641da767e4/lib/definitions/object_definitions.js#L122

kann ich das einfach in einem Patch auf true setzten? oder wie ist das gedacht?

**Comment by Jey-Cee** [comment]
Hi Holger, 
freut mich das du dich beteiligst. 
Das write flag kann man im eep einfach auf true setzen. Ist sicher ein C&P Fehler, den aber noch niemand bemerkt hat.
