### ISSUE TITLE
Micropelt MVA009

### ISSUE THREAD

**Issue by f-io** [Jey-Cee/ioBroker.enocean#178]
**Manufacturer**: MICROPELT
**Model**: MVA009
**Production date/period**: 05/2023
**Link to product**: https://micropelt.atlassian.net/wiki/download/attachments/184221711/Micropelt_MVA009%20(EN)_DS_0523.pdf?api=v2

More or less similar to MVA005 in terms of radio communication (A5-20-06).

Are merge request welcome?

**Comment by Jey-Cee** [comment]
Yes, PR is welcome.

**Comment by Jey-Cee** [comment]
PR #183 merged
