### ISSUE TITLE
TeachIn Probleme mit FJ62NP-230V

### ISSUE THREAD

**Issue by rapacides** [Jey-Cee/ioBroker.enocean#18]
**Describe the bug**  
Hallo,

ich habe das Problem, dass der TeachIn bzw. die Steuerung meines FJ62NP-230V nicht richtig funktioniert.
Der TeachIn wird zum einen vom Aktor nicht bestätgt, zum anderen können keine Befehle an den Aktor gesenden werden.
Interessanterweise werden aber die Staus-Meldungen empfagen.

**To Reproduce**  
Der Fehler ist immer aufgetreten, sowohl bei einem Aktor welcher schon eingelernt war (FHEM) als auch nach einem Werksreset.
Auch das ein bzw. ausschalten der Bestätigungstelegramme hat keinen Unterscheid ergeben.

**Screenshots & Logfiles**  
enocean.0 | 2020-12-27 14:57:59.040 | warn | (630) The data length for a 4BS telegram is incorrect. The length is 0
-- | -- | -- | --
enocean.0 | 2020-12-27 14:57:59.030 | info | (630) state 04111585.CMD changed: 4 (ack = false) state:  {"val":4,"ack":false,"ts":1609077479024,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1609077479024}

**Versions:**  
 - Adapter version: 0.3.0
 - JS-Controller version: 3.1.6
 - Node version: v12.20.0
 - Operating system: docker-image on rasberrypi (debian)

**Comment by Jey-Cee** [comment]
Danke für die Meldung ich werd mir das anschauen sobald ich kann.

**Comment by Jey-Cee** [comment]
Mit der Version 0.3.1 ist das Problem behoben. Du musst nur alle Objekte für das Gerät löschen und das Gerät neu anlegen.
