### ISSUE TITLE
[Bug]: Probleme mit dem Parser

### ISSUE THREAD

**Issue by Holger-Will** [Jey-Cee/ioBroker.enocean#180]
mir ist gestern aufgefallen, dass alle Telegramme mit 0x00 enden...
der bug war relativ einfach zu finden... die Telegramme sind nämlich alle ein Byte zu kurz. hier:
 https://github.com/Jey-Cee/ioBroker.enocean/blob/42a73a5220f68be437fa2154c15966a4af012645/lib/tools/Serialport_parser.js#L88
sollte es `this.position+1` heißen.

Bei der Gelegenheit habe ich den Parser mal an meiner Parser Test Suite ausprobiert. Und obwohl sich der Parser sehr gut schlägt gibt es einige Tests die failen... 

für enocean-js hatte ich mir damals mal die Mühe gemacht den Referenz Parser, der [ab Seite 95 in der Spezifikation](https://github.com/enocean-js/enocean-js/blob/master/resources/enocean-specification/PDF/EnOceanSerialProtocol3_CustomerRelease_v1p47.pdf) angegeben ist, 1 zu 1 in JS zu implementieren... 

Dieser Parser wird so in quasi allen Gateways, Aktoren und in den offiziellen Bibliotheken verwendet.
Ich habe allerdings nur einen ESP3 Parser :-(
Wie stehst Du dazu den Parser aus enocean-js zu übernehmen? 
Ich müsste den wahrscheinlich ein wenig an Deine ESP3Packet Implementierung anpassen, aber das sollte mit wenig Aufwand zu erledigen sein.

Wahrscheinlich gibt es so eine Referenz Implementierung auch für ESP2. Das könnte man dann auch in Angriff nehmen.

Alternativ kann ich für den o.a. Fehler auch einen PR einreichen, den Parser würde ich dann erstmal in ruhe lassen.

**Comment by Jey-Cee** [comment]
Grundsätzlich habe ich kein Problem wenn du deinen ESP3 Parser Portierst. Ich hatte ihn damals nicht verwendet weil in ioBroker keine esm Module verwendet werden können.
Da das eine größere Änderung ist müssen wir die dann in einem Sepperaten Branch machen und Testen lassen.

ESP2 hat für mich Übrerhaupt keine Relevanz, weil das schon so alt ist das man kaum mehr Hardware dazu findet.

**Comment by Holger-Will** [comment]
alles klar, dann guck ich mir das mal an...
