### ISSUE TITLE
[Bug]: wrong EEP ID for device type Eltako FTKE

### ISSUE THREAD

**Issue by stefanhofmann2** [Jey-Cee/ioBroker.enocean#185]
### What happened?

Trying to add a new EnOcean device from Eltako FTKE window contact result in a wrong  EEP id see mapping below
   "FTKE": {
      "EEP": [
        "TF-13-02"
      ],
should be F6-10-00 !!!

### Adapter Version

v0.9.1

### JS-Controller Version

5.0.12

### Node JS Version

v18.17.1

### NPM Version

9.6.7

### Operating System

Debian

**Comment by Jey-Cee** [comment]
No this is not wrong. 
F6-10-00 knows open, closed and tilt. 
The ftke only knows open and closed, for this reason it has its own EEP in ioBroker.
