### ISSUE TITLE
Question concerning EEP A5-20-06

### ISSUE THREAD

**Issue by stefanhofmann2** [Jey-Cee/ioBroker.enocean#186]
Hello @Jey-Cee,
i have a micropelt MVA-09 radiator. It works so far, but i am wondering that in the object view there is no SPS set parameter shown.
This parameter may be used to switch between valve position mode and temperatur set point using internal temp. controller.
How can i add this parameter?

Greetings
Stefan

**Comment by Jey-Cee** [comment]
Seems this Profile was not implemented in the correct way. I will have a look.

**Comment by Jey-Cee** [comment]
Fixed with version 0.9.3
