### ISSUE TITLE
usb300 cannot read "/dev"   

### ISSUE THREAD

**Issue by pw2211** [Jey-Cee/ioBroker.enocean#187]
Hallo Jey-Cee,

das USB300 Modul wird beim Geräte hinzufügen nicht erkannt.

EnOcean HF-Modul 868MHz bis 125Kbit/s UART, USB

Mac-Mini USB-Anschluss:  /dev/tty.usbserial-EO7DLOXL

Logfile:

enocean.0 | 2023-10-27 17:15:40.280 | error | Cannot read "/dev": Error: ENOENT: no such file or directory, scandir '/dev/serial/by-id'

enocean.0 | 2023-10-27 17:15:40.246 | info | ["/dev/tty.usbserial-EO7DLOXL"]
enocean.0 | 2023-10-27 17:15:40.246 | error | Cannot read "/dev": Error: ENOENT: no such file or directory, scandir '/dev/serial/by-id'

admin.0 | 2023-10-27 17:15:40.232 | info | ==> Connected system.user.admin from ::ffff:192.168.5.105
enocean.0 | 2023-10-27 17:15:22.728 | info | {"BaseID":"ff880b80","Frequency":"868.3 Mhz","Protocol":"ERP1","AppVersion":"2.15.0.0","ApiVersion":"2.6.9.0","ChipID":"05231017","ChipVersion":"454f0103","AppDescription":"GATEWAYCTRL"}

enocean.0 | 2023-10-27 17:15:22.596 | info | starting. Version 0.9.0 in /usr/local/iobroker/node_modules/iobroker.enocean, node: v20.9.0, js-controller: 5.0.12
host.Mac-mini-von-Peter.fritz.box | 2023-10-27 17:15:22.369 | info | instance system.adapter.enocean.0 started with pid 4622

LG Peter

**Comment by Jey-Cee** [comment]
Was heist wird nicht erkannt? Kannst du es nicht auswählen in der Konfiguration?
Beim Adapterstart werden jedenfalls die Daten von einem EnOcean Stick ausgelesen.

**Comment by pw2211** [comment]
Der Adapter findet meinen enOcean Schalter PTM 215Z (Hersteller Gira) nicht.

Liegt eventuell an dem Schalter selber, da es eine Zigbee-Variante  ist.

Der Zigbee-Adapter findet ihn beim einrichten, kann aber die Schaltsignale nicht empfangen.

Danke für die Rückmeldung.

**Comment by Jey-Cee** [comment]
Ja Zigbee ist kein EnOcean. Deswegen kann er nicht mit dem EnOcean Adapter verwendet werden. 
Es ist etwas Unglücklich das es EnOcean als Marke und als Funkstandard gibt.

**Comment by pw2211** [comment]
Danke für die Info.LG PeterAm 01.11.2023 um 12:07 schrieb Christoph Gerle ***@***.***>:﻿
Ja Zigbee ist kein EnOcean. Deswegen kann er nicht mit dem EnOcean Adapter verwendet werden.
Es ist etwas Unglücklich das es EnOcean als Marke und als Funkstandard gibt.
