### ISSUE TITLE
FSR14x4 schaltet nicht mehr

### ISSUE THREAD

**Issue by Jaaannis** [Jey-Cee/ioBroker.enocean#19]
**Describe the bug**  
Adapter reagiert nach Update auf 0.3.0 nicht mehr auf Schaltversuche.

**To Reproduce**  
CMD schalten auf 1 oder 0  (FSR14x4)

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/60622519/103442127-bbb30400-4c53-11eb-85ba-bb6f977d8b7e.png)

Version 0.3.0 in /opt/iobroker/node_modules/iobroker.enocean, node: v12.20.0, js-controller: 3.1.6

**Comment by Jey-Cee** [comment]
Sieht aus als würde im Objekt gateway der Eintrag BaseID unter native fehlen. Von Welcher Version bist du gekommen?
