### ISSUE TITLE
Enocean IOBroker

### ISSUE THREAD

**Issue by mundl13** [Jey-Cee/ioBroker.enocean#190]
Hallo !
Ich überwache mehrere Nodon relais mit fhem. Ich möchte aber zu IOBroker wechseln. Leider habe ich die relais verbaut und schon mit Loxone angelernt. = anlernen nicht erwünscht. Fhem fondet die relais von alleine... Der EnOcean adapter for ioBroker findet leider nicht von alleine...Bitte um Hilfe. Der USB stick bzw. der Adapter ist aktiv. bzw. läuft. Rechts oben Blaue Fläche erkennt 
Zuletzt gesehene Geräte-ID: 019160b9 . diese können aber nicht angelegt werden.

**Comment by Jey-Cee** [comment]
Hallo mundl,
das hier ist nicht der Richtige Ort für Fragen zur Benutzung, dafür haben wir das Forum. 
Es ist nicht vorgesehen die Aktoren ohne Anlernen mit dem ioBroker zu verbinden. 
Wenn du sie aber schon mit Loxone verbunden hast, kannst du sie dann nicht mit Loxone Überwachen?

**Comment by mundl13** [comment]
Sorry für die Störung.Loxone hat mit Enocean nicht so eine Freude….Nodon Relai gibt leider kein Signal zurück, steht in mehreren Foren. Daher die Überwachung.MfG Roland Von meinem iPhone gesendetAm 25.11.2023 um 09:59 schrieb Christoph Gerle ***@***.***>:﻿
Hallo mundl,
das hier ist nicht der Richtige Ort für Fragen zur Benutzung, dafür haben wir das Forum.
Es ist nicht vorgesehen die Aktoren ohne Anlernen mit dem ioBroker zu verbinden.
Wenn du sie aber schon mit Loxone verbunden hast, kannst du sie dann nicht mit Loxone Überwachen?

**Comment by Jey-Cee** [comment]
Ok ich hatte erwartet das die Integration in Loxone besser ist, aber hab damit noch nie gearbeitet.

Was du machen kannst im ioBroker: Der Adapter hat die DPs lastID und lastTelegram unter Gateway. Die kannst du je nach bedarf mit einem Script auswerten.

**Comment by Jey-Cee** [comment]
Ah was auch geht, als Taster PTM210 im Adapter anlernen. Der Aktor sendet seinen Status wie ein Taster.

**Comment by mundl13** [comment]
Danke Danke werde ich nächste Woche gleich probieren..MfG Roland Von meinem iPhone gesendetAm 25.11.2023 um 13:38 schrieb Christoph Gerle ***@***.***>:﻿
Ah was auch geht, als Taster PTM210 im Adapter anlernen. Der Aktor sendet seinen Status wie ein Taster.

**Comment by Jey-Cee** [comment]
Hats geklappt?

**Comment by mundl13** [comment]
Ja danke … dein Tipp war sehr hilfreich.MfG Roland Von meinem iPhone gesendetAm 26.01.2024 um 20:43 schrieb Christoph Gerle ***@***.***>:﻿
Hats geklappt?

**Comment by Jey-Cee** [comment]
Top, dann kann ich hier schließen?
