### ISSUE TITLE
Set Temperature on Oventrop R-Tronic RT B

### ISSUE THREAD

**Issue by kimzeuner** [Jey-Cee/ioBroker.enocean#200]
Hello, 
i have integrated my Oventrop R-Tronic RT B (Enocean) and it seems to work fine. In the next step i tried to send the setpoint temperature from iobroker to the device but it is not working. I have used the script as described in the devices.json file an started the teach in process again. 
After that i have created a script that sets the value of the SP after the RSSI is updated (as it says in the description that it is possible to send the temperature within 1 second). The value is set correctly in iobroker but it is not transferred to the device.
Can you please give me a hint what i can/must do ?
Thanks in advance!

**Comment by Jey-Cee** [comment]
Hi, 
did you setup your RT B as A5-10-06 + RPS? Check the device configuration at the RT B.

**Comment by kimzeuner** [comment]
Yes i did. 
![image](https://github.com/user-attachments/assets/0241fd79-c609-4ba0-81c2-4c4d69dc0342)
I think it is possible that i did something wrong as i just started with iobroker because of the possibilty to pair the rt b so any newbie hint is welcome.

**Comment by Jey-Cee** [comment]
`on({id: \"enocean.0.DeviceID.rssi\"}, () => { setState(\"enocean.0.DeviceID.CMD\", 1) })`

Did you replace DeviceID with the real ID of the device?

**Comment by kimzeuner** [comment]
Yes, also did that. my script looks like this 
```
on({id: "enocean.0.059499FD.rssi"}, () => { setState("enocean.0.059499FD.CMD", 1) })
```
i had to delete the \ because i got errors before. 
after an RSSI update i can see the change of the CMD State from 0 to 1 so the script seems to work.
How should the script for sending the setpoint look ? 
Mine looks like this at the moment (i created it with blockly and for better reading here i copied the js code)
```
on({ id: 'enocean.0.059499fd.rssi' /* Signal Strength */, change: 'any' }, async (obj) => {
  let value = obj.state.val;
  let oldValue = obj.oldState.val;
  setState('enocean.0.059499fd.SP' /* Sollwert */, '105', true);
  setState('enocean.0.059499fd.CMD' /* Befehl */, '0', true);
});
```
in this script i tried 0 and also 1 at the end for the CMD state.

**Comment by Jey-Cee** [comment]
The script its self looks good, but the values are written as string which has to be a number.
I am not sure actual if the set point value is 0-255 or in °C. Test it with a value between 0 and 30°C

**Comment by kimzeuner** [comment]
i tried both, setting a number instead of a string and use °C instead of 0-255 but it doesn`t work. 
is it possible that it takes more than 1 second until my command is sent back to the rt b ? is there any possibility to check that ?

**Comment by kimzeuner** [comment]
Should there be a sender id ? if yes, how can i achieve that ? 
![Bildschirmfoto 2024-08-18 um 13 55 32](https://github.com/user-attachments/assets/92b362b5-66a1-491d-8db5-de0e9e86dc56)

**Comment by Jey-Cee** [comment]
You can change the log level for the instance from info to debug. Then all telegrams will be printed to the log.
Go to config of the instance and change it where the version is shown near the play (pause) symbol is shown. 

No Sender id is ok for this device.

**Comment by kimzeuner** [comment]
I think it is finally working.
Thanks a lot for your hints. Just for documentation reasons if anyone comes along this issue:
In the Logs i saw, that no message was sent. After some trying i found out that i had to chenge the blockly command from "refresh state ..." to "control state ...". It now looks like this:
![image](https://github.com/user-attachments/assets/3c99fd7b-1c23-435b-9a54-068dbdd656f6)
After that i saw in the Logs that the message was sent.

This lead me to the idea that i had to change it in the teach-in script too. So i changed that and started the teach-in on my rt b again. For the first time i got the message "Successfull" on my rt b. Before it was only "Telegram sent". I have also seen that in the Diagnostics of the Device there is now also the Gateway ID of my USB300 Stick listed.

After the next update message from the rt b the script was executed and the target temperature was set as i configured it in the script.

Again, thanks for your help!

**Comment by Jey-Cee** [comment]
Thanks for explaning your problem and the solution
