### ISSUE TITLE
Wrong format 

### ISSUE THREAD

**Issue by hash99** [Jey-Cee/ioBroker.enocean#21]
Hi,
by starting the Enocean-Adapter I got the error:
Caught by controller[0]: SyntaxError: /opt/iobroker/node_modules/iobroker.enocean/eep/EEP2IOB.json: Unexpected token / in JSON at position 6321
and 
Caught by controller[0]: ^. 
I think the son has the wrong format. I Found '^M' in the file after installing. 
Please check. I use a raspberrypi and and iobroker.admin 3.4.3.
Thank you for your support.

**Comment by Jey-Cee** [comment]
Thank you for your report, it is fixed.
