### ISSUE TITLE
Hoppe Fenstergriff SecuSignal / ConnectHome

### ISSUE THREAD

**Issue by sky-it** [Jey-Cee/ioBroker.enocean#21]
**Manufacturer**: Hoppe (7FF)
**Model**: SecuSignal + ConnectHome
**Production date/period**: N/A
**Link to product**: [Link 1](https://www.hoppe.com/de/de/fenstergriffe/hoppe-innovationen/efenstergriff-secusignal) - [Link 2](https://www.hoppe.com/de/de/fenstergriffe/hoppe-innovationen/efenstergriff-connecthome) 

Vergleichbar mit diesem [Issue](https://github.com/Jey-Cee/ioBroker.enocean/issues/16)

EEP: F6-10-00
 #Teach-Methode?: RPS

```
  "HOPPE": {
    "SecuSignal": {
      "EEP": ["F6-10-00"],
      "autocreate": true,
      "teachin_method": "RPS",
      "id_offset": false,
      "help": {
        "en": {
          "1": "Click on 'Add Device'.",
          "2": "Start teachin mode"
        },
        "de": {
          "1": "Auf 'Gerät Hinzufügen' klicken.",
          "2": "Teach-In starten."
        }
      }
    }
  },
```

**Comment by Jey-Cee** [comment]
Danke das du die definition erstellt hast.
In version 0.3.1

**Comment by sky-it** [comment]
Als Eltako FHF wird der SecuSignal perfekt erkannt, als Hoppe SecuSignal bekommt er die EEP F6-02-00 zugeordnet.

**Comment by Jey-Cee** [comment]
Habs gerade gefixt.
