### ISSUE TITLE
Thermokon SR04 zeigt negative Vorzeichen

### ISSUE THREAD

**Issue by spheara** [Jey-Cee/ioBroker.enocean#22]
**Describe the bug**  
Die Messwerte werden mit negativen Vorzeichen ausgegeben. 
Beispiel: 18°C wird als -18°C ausgegeben.

**Screenshots & Logfiles**  
![2021-01-18 (2)](https://user-images.githubusercontent.com/77607860/104886015-4a6c9400-5969-11eb-941a-7af5a405e847.png)

**Versions:**  
 - Adapter version: 0.3.0
 - JS-Controller version: 4.8.4
 - Node version: v12.20.1

**Comment by Jey-Cee** [comment]
Falscher Adapter.
