### ISSUE TITLE
Eltako Energy monitor FSS12

### ISSUE THREAD

**Issue by warlord1977** [Jey-Cee/ioBroker.enocean#26]
**Manufacturer**: ELTAKO
**Model**: FSS12-12V DC
**EEP**:  A5-12-01
**Production date/period**: since week 42 / 2012
**Link to product**: https://www.eltako.de/product/professional-standard/drehstromzaehler-und-wechselstromzaehler/fss12-12v-dc/

[FSS12_30100600-4_dt.pdf](https://github.com/Jey-Cee/ioBroker.enocean/files/5864641/FSS12_30100600-4_dt.pdf)

**Comment by Jey-Cee** [comment]
In version 0.3.2
