### ISSUE TITLE
FL62-230V Einlernprozedur

### ISSUE THREAD

**Issue by mustangix** [Jey-Cee/ioBroker.enocean#35]
Nach dem in Version 0.3.1 implementierten Einlernvorgang ist der Aktor nicht steuerbar. Er wird erst steuerbar, wenn während der Lernphase des Aktors noch ein TeachIn-Kommando von ioBroker aus gesendet wird. ( siehe auch meinen Beitrag https://forum.iobroker.net/topic/37331/test-adapter-enocean-2-v0-3-x/402# )
Vielleicht ist das ja in einer künftigen Version machbar.
Vielen Dank

**Comment by Jey-Cee** [comment]
> Vielleicht ist das ja in einer künftigen Version machbar.

Was genau soll gemacht werden? Irgendwie steh ich auf dem Schlauch was du mir sagen willst.
