### ISSUE TITLE
Viessmann/Afriso Klimasensor (7554507 bzw. FTM T ) / Temperatursensor (7554951 bzw. FTM TF)

### ISSUE THREAD

**Issue by ioBroker-User** [Jey-Cee/ioBroker.enocean#36]
**Manufacturer:** Viessmann/Afriso 
 **Model:** Klimasensor (7554507 bzw. FTM T ) / Temperatursensor (7554951 bzw. FTM TF) 
 **Production date/period:** ab 2015 
 **Link to product:** https://www.afriso.com/ix_pim_assets/PDF/2/82/282/Funktransmitter-FTM-T-TF-DB.pdf 
 
A5-02-05 (Temperatursensor bzw. FTM T) / A5-04-01 (Klimasensor bzw. FTM TF) - Viessmann und Afriso sind baugleich!

**Comment by Jey-Cee** [comment]
In version 0.3.2
