### ISSUE TITLE
Trio2Sys Aussentemperatursensor -30°C bis +50°C

### ISSUE THREAD

**Issue by ioBroker-User** [Jey-Cee/ioBroker.enocean#42]
**Manufacturer:** Trio2Sys 
 **Model:** Aussentemperatursensor -30°C bis +50°C 
 **Production date/period:** Keine Angaben 
 **Link to product:** http://www.trio2sys.fr/index.php/en/products/probes/38 
 Laut Hersteller EEP = A5-02-13

**Comment by Jey-Cee** [comment]
In version 0.3.5
