### ISSUE TITLE
NODON PIR-2-1-01 Bewegungs-Sensor

### ISSUE THREAD

**Issue by ioBroker-User** [Jey-Cee/ioBroker.enocean#43]
**Manufacturer:** NODON 
 **Model:** PIR-2-1-01 Bewegungs-Sensor 
 **Production date/period:** 2019 
 **Link to product:** https://nodon.fr/en/nodon/enocean-motion-sensor/ 
 EEP: A5-07-03

**Comment by Jey-Cee** [comment]
In version 0.3.5
