### ISSUE TITLE
Eltacko FMS14

### ISSUE THREAD

**Issue by ioBroker-User** [Jey-Cee/ioBroker.enocean#44]
**Manufacturer:** Eltacko 
 **Model:** FMS14 
 **Production date/period:**  
 **Link to product:** https://www.eltako.de/product/professional-smart-home/baureihe-14-rs485-bus-reiheneinbaugeraete-fuer-die-zentrale-gebaeudefunk-installation-professional-smart-home/fms14/

**Comment by Jey-Cee** [comment]
Production period <32/19 in version 0.3.6
