### ISSUE TITLE
warnungen im log admin 5

### ISSUE THREAD

**Issue by JackDaniel007** [Jey-Cee/ioBroker.enocean#55]
adapter version 0.3.6

`enocean.0 | 2021-05-13 06:50:51.309 | warn | Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "01a5bd01"

enocean.0 | 2021-05-13 06:49:11.232 | warn | Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "01a5bd01"

enocean.0 | 2021-05-13 06:45:51.093 | warn | Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "01a5bd01"

enocean.0 | 2021-05-13 06:44:11.011 | warn | Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "01a5bd01"

enocean.0 | 2021-05-13 06:43:58.060 | warn | Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "05057e7d"`

**Comment by mane444** [comment]
Ist bei mir auch:
JS 3.3.5
Admin 5.0.15

<html>
<body>


enocean.0 | 2021-05-14 12:28:32.327 | warn | (1259) Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "0590176e"
-- | -- | -- | --
enocean.0 | 2021-05-14 12:28:32.147 | warn | (1259) Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "05839880"
enocean.0 | 2021-05-14 12:28:32.008 | warn | (1259) Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "0583987c"
enocean.0 | 2021-05-14 12:28:30.475 | warn | (1259) Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "ffef578b"
enocean.0 | 2021-05-14 12:28:30.391 | info | (1259) State value to set for "enocean.0.0590176e.CMD" has to be type "number" but received type "undefined"
enocean.0 | 2021-05-14 12:28:30.386 | info | (1259) State value to set for "enocean.0.0590176e.DS" has to be type "number" but received type "undefined"
enocean.0 | 2021-05-14 12:28:30.327 | warn | (1259) Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "ffef5789"
enocean.0 | 2021-05-14 12:28:30.242 | info | (1259) State value to set for "enocean.0.05839880.CMD" has to be type "number" but received type "undefined"
enocean.0 | 2021-05-14 12:28:30.236 | info | (1259) State value to set for "enocean.0.05839880.DS" has to be type "number" but received type "undefined"
enocean.0 | 2021-05-14 12:28:30.174 | warn | (1259) Read-only state "enocean.0.gateway.lastID" has been written without ack-flag with value "ffef5788"
enocean.0 | 2021-05-14 12:28:30.089 | info | (1259) State value to set for "enocean.0.0583987c.CMD" has to be type "number" but received type "undefined"
enocean.0 | 2021-05-14 12:28:30.084 | info | (1259) State value to set for "enocean.0.0583987c.DS" has to be type "number" but received type "undefined"


</body>
</html>

**Comment by Jey-Cee** [comment]
Ist in der 0.3.7 behoben.
