### ISSUE TITLE
permundo PSC 234

### ISSUE THREAD

**Issue by ttbahnfan** [Jey-Cee/ioBroker.enocean#64]
**Manufacturer**:permundo
**Model**:PSC 234
**Production date/period**:?
**Link to product** EEP A5-38-08 Steuerung
D2-01-09 Steuerung und Energiemessung

**Comment by ttbahnfan** [comment]
Ich kann den Plug schalten, aber leider keine Leistungswerte empfangen

**Comment by Jey-Cee** [comment]
Wie hast du ihn den angelernt?

**Comment by ttbahnfan** [comment]
Virtuellen Schalter, PSC 234 in Anlernmodus und dann CMD im Objektbaum betätigt!


Am 02.06.2021 um 20:34 schrieb Christoph Gerle ***@***.******@***.***>>:



Wie hast du ihn den angelernt?

**Comment by Jey-Cee** [comment]
Gerät ist jetzt in der Liste und kann getestet werden.

**Comment by hearp** [comment]
Leider ist es mir nicht gelungen, den Permundo PDC234 anzulernen.
Der Log sagt:
- Create objects for NAN-NAN-NAN from undefined with id: 01908cba
- EEP NAN-NAN-NAN unknown, send this information to developer.

**Comment by Jey-Cee** [comment]
@hearp welche Adapter version hast du installiert

**Comment by hearp** [comment]
0.5.4
Ich habe die Prozedur mehrfach versucht, um auch sicher zu stellen, daß der PDC wirklich anlernbereit ist ... immer die selben beiden Meldungen.

**Comment by Jey-Cee** [comment]
Meinst du wirklich einen **PDC234**? Hier geht es um den PSC234.
Ich hab keinen zum Testen hier, aber einen anderen der die selbe Teachin Methode verwendet und konnte ihn anlernen.
Allerdings hatte ich auch einmal die selbe Meldung wie du, sie schien durch ein Telegram von einem anderen Gerät ausgelöst zu werden.
Kannst du mir bitte mal das log zur Verfügung stellen und die ID von deinem Gerät.
