### ISSUE TITLE
permundo PSC 152

### ISSUE THREAD

**Issue by ttbahnfan** [Jey-Cee/ioBroker.enocean#65]
**Manufacturer**:permundo
**Model**:PSC 152
**Production date/period**:?
**Link to product**:EEP A5-38-08 Steuerung
A5-11-03 Status: Position
D2-01-09 teilweise (Energiemessung & erweiterte Konfiguration)

**Comment by ttbahnfan** [comment]
Ich kann mit diesen Rolladenaktor nur hoch und runter aktivieren. Position und Leistungswerte sind leider nicht darstellbar.
Würde mich freuen, wenn Du diesen Aktor mit einarbeiten könntest.
Vielen Dank im Voraus!

Peter Streuber

**Comment by Jey-Cee** [comment]
Kannst du mir einen PSC 152 zur Verfügung stellen damit ich den richtig Implementieren kann?

**Comment by ttbahnfan** [comment]
Hallo Christoph,
ich würde dann den Aktor bei mir ausbauen und Dir zuschicken!
Teile mir bitte Deine Adresse mit!

Nochmals vielen Dank für Deine Bemühungen

Peter

Am 03.06.2021 um 23:44 schrieb Christoph Gerle ***@***.***>:

﻿

Kannst du mir einen PSC 152 zur Verfügung stellen damit ich den richtig Implementieren kann?
