### ISSUE TITLE
HOPPE eFenstergriff ConnectHome

### ISSUE THREAD

**Issue by ioBroker-User** [Jey-Cee/ioBroker.enocean#68]
**Manufacturer:** HOPPE 
 **Model:** eFenstergriff ConnectHome 
 **Production date/period:** 2020 
 **Link to product:** https://www.hoppe.com/de-de/fenstergriffe/hoppe-innovationen-fenstergriffe/efenstergriff-connecthome/ 
 EEP F6-10-00

**Comment by Jey-Cee** [comment]
In version 0.3.9
