### ISSUE TITLE
ON command Eltako  FUD14

### ISSUE THREAD

**Issue by Chrisego2** [Jey-Cee/ioBroker.enocean#69]
**Eltako FUD14 on schaltet nicht ein.
 level wird nicht auf 100% gesetzt.*  

**Expected behavior** 
CMD o  sollte Sommer auf 100% schalten

**Versions:**  
 - Adapter version: <0.3.8>

**Comment by Jey-Cee** [comment]
Danke fürs melden, wird im nächsten release gefixt sein.
