### ISSUE TITLE
Thermokon SR MDS (Solar)

### ISSUE THREAD

**Issue by KLVN** [Jey-Cee/ioBroker.enocean#76]
**Manufacturer**: Thermokon
**Model**: SR MDS (Solar)
**Production date/period**: 2012-*
**Link to product**:
* Mein Gerät: https://shop.akktor.de/SR-MDS-Solar-Bewegungssensor-mit-Helligkeitsmessung
* Nachfolger: https://www.thermokon.de/direct/categories/sr-mds-solar?path=%2F1%2F2%2F20%2F24%2F65%2F67&filter_articles=1
* Datenblatt: https://www.thermokon.de/direct/alterra-base/mimes/get/22a8605078ae26aa2

Wählbare Telegramme:
* EEP A5-08-01 (Standard)
* EEP F6-02-01
* EEP A5-06-02
* EEP A5-07-01
* EEP A5-07-02
* EEP A5-07-03
* EEP A5-08-02

![image](https://user-images.githubusercontent.com/8047980/129561446-96ff9f76-f551-438f-af7a-959aea5e6426.png)

Über das Programm "airConfig" von Thermokon kann man die einzelnen Telegramme für unterschiedliche Funktionen einstellen. Mir fehlt noch der Treiber für den USB300-Stick, deshalb kann ich zu diesem Zeitpunkt dort noch keine Einstellungen vornehmen und ich weiß auch nicht, mit welcher Telegramm-Einstellung der Bewegungsmelder geliefert wurde (ebay Kleinanzeigen) **EDIT: A5-08-01**. Die ID lässt sich mit deinem EnOcean-Adapter aber schon empfangen.

**Comment by KLVN** [comment]
Testweise habe ich den Thermokon SR MDS als einen Eltako FBH65S (quasi der gleiche Bewegungsmelder) eingebunden und das funktioniert soweit (EEP TF-13-13).

**Comment by Jey-Cee** [comment]
Kommt in der nächsten version

**Comment by KLVN** [comment]
Funktioniert super! Die Werte für die Helligkeit haben allerdings einen Faktor von 0.1, im Vergleich zu einem anderen Bewegungsmelder (https://github.com/Jey-Cee/ioBroker.enocean/issues/24), wenn diese nebeneinander positioniert sind. Kann ich im Nachhinein einfach mit 10 multiplizieren, aber vielleicht kennst du dich da besser mit den jeweiligen Protokollen aus. Ist das eine bewusste Entscheidung, um bei der Übertragung Daten zu sparen und man es deshalb sowieso später noch korrigieren muss?

**Comment by Jey-Cee** [comment]
Schau ich mir nochmal an.

**Comment by Jey-Cee** [comment]
Du schreibst die beiden Bewegungsmelder liegen um den Faktor 10 auseinander. Gib mir mal für beider Bewegungsmelder einen Werte.

**Comment by KLVN** [comment]
Muss kein Fehler des Adapters sein (denke ich auch nicht), war nur eine generelle Frage, ob dir sowas schon mal vorgekommen ist.

Laut Datenblatt wird auch standardmäßig nur von 0 bis 510 Lux gemessen und der Modus ließe sich noch auf 0...1000 Lux (~2^10) umstellen. Es ist mir nur aufgefallen, dass es immer fast exakt die Hälfte vom anderen Bewegungsmelder ist.
![image](https://user-images.githubusercontent.com/8047980/133846938-553e8239-6de1-4636-9cc0-c5b26b52cf1d.png)

Ich sehe gerade, dass mein [anderer Melder von 0...2048 Lux misst](https://wiki.fhem.de/wiki/EnOcean-FBH65S-Funk-Bewegungs-_Helligkeitssensor#:~:text=Helligkeit%20von%200%20bis%202048%20Lux%2C%20256%20verschiedene%20Werte%20(8%20Bit%20Aufl%C3%B6sung)), aber nur mit 256 (8 Bits) Werten und nicht allen 2048.

Ich hoffe man kann es erkennen. Links ist der erste Melder mit den höheren Werten ("Opus"); Rechts der Melder aus diesem Issue ("Thermokon").
Die Kurven sind sich ähnlich (zumindest kann man den Verlauf erahnen), doch die Skala ist unterschiedlich. Beispiel: Zwischen 10 und 12 Uhr sind es links etwas über 150 Lux und rechts etwas über 15 Lux.
![image](https://user-images.githubusercontent.com/8047980/133848100-514a42f6-33a4-476f-a307-f37db2de78ee.png)


Wie gesagt, war nur so eine generelle Frage. Ich muss wohl nochmal ein richtiges Messgerät daneben legen, um die beiden Melder zu "kalibrieren". So genau bzw. die echten Werte brauche ich auch gar nicht, weil ich die Lux-Werte für andere Dinge sowieso nur nach Gefühl einstelle und beide Melder letztendlich in unterschiedlichen Räumen sein sollen.

**Comment by Jey-Cee** [comment]
Ich hab nur einen Typ von Helligkeitssensor in Betrieb und konnte bisher keine vergleiche anstellen.
Das es um Faktor 10 auseinander liegt finde ich komisch. Wenn es alleine ein Fehler in der Berechnung des Wertes wäre, wäre es entweder die hälfte oder ein viertel.  

Du hast den SR aber schon mit A5-08-01 angelegt und nicht mit einem der anderen Profile?

**Comment by KLVN** [comment]
Na zumindest sind die Werte nicht völlig unterschiedlich :D

> Du hast den SR aber schon mit A5-08-01 angelegt und nicht mit einem der anderen Profile?

Ja, der läuft mit A5-08-01. Habe genau die Modellbezeichnung aus der Adapter-Version von vor ca. 2 Wochen benutzt. Ich sehe gerade, dass ich den anderen Melder als "ELTAKO FBH65S" eingerichtet habe, es aber der "OPUS GN-BH63AP-pw" ist. Andererseits ist es quasi/exakt das gleiche Modell und beide haben im Adapter TF-13-13. [[1]](https://github.com/Jey-Cee/ioBroker.enocean/blob/c94cfa2a544a7495e72bc389ea6e21f31ce17370/lib/definitions/devices.json#L343)[[2]](https://github.com/Jey-Cee/ioBroker.enocean/blob/c94cfa2a544a7495e72bc389ea6e21f31ce17370/lib/definitions/devices.json#L2753)

[Beim FHEM Wiki](https://wiki.fhem.de/wiki/EnOcean-FBH65S-Funk-Bewegungs-_Helligkeitssensor#:~:text=%22subType%20lightTempOccupSensor.01%22%20kennzeichnet%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Light%2C%20Temperatur%20and%20Occupancy%20Sensor%20(EEP%20A5-08-01)) sehe ich jetzt, dass der FBH65S (und damit auch der OPUS) wohl doch A5-08-01 ist. Im Artikel aus 2015 gibt es einen Screenshot der empfangenen Daten und dort ist es auch A5-08-01 (letzte Zeile): https://www.meintechblog.de/wordpress/wp-content/uploads/2015/03/Opus-greenNet-Bewegungssensor.jpg

Bevor du gleich ungetestet beide EEPs (FBH(S)65/OPUS) auf A5-08-01 änderst, würde ich meinen OPUS sonst erstmal von TF-13-13 auf A5-08-01 stellen und mich morgen Abend mit den neuen Kurvendiagrammen melden.

**Comment by Jey-Cee** [comment]
Der Unterschied zwischen A5-08-01 und TF-13-13 ist der Messbereich. In sofern hab ich nicht vor das zu ändern. 
Mich interessiert aber was dein versuch ergibt.

**Comment by KLVN** [comment]
Links: OPUS (jetzt mit A5-08-01); Rechts: THERMOKON (immer noch mit A5-08-01):
![image](https://user-images.githubusercontent.com/8047980/133897894-3b5228a5-0d9e-4597-aadd-0914ed329aee.png)

Skala habe ich bei beiden angepasst, damit sie auf dem Bildschirm ähnlich aussehen.
Hier paar Messwerte im direkten Vergleich:
| Zeit  | Opus (Lux) | Thermokon (Lux)  |
|-------|------------|----------------|
| 9:00  | 16          | 6|
| 10:00 | 34         | 14|
| 12:00 | 56         | 20|
| 13:00 | 12         | 8|
| 17:00 | 32         | 12|

(Bemerkung: Der Tag war heute etwas dunkler als gestern)
