### ISSUE TITLE
Omnio WS / R101 - PTM210

### ISSUE THREAD

**Issue by ioBroker-User** [Jey-Cee/ioBroker.enocean#78]
**Manufacturer:** Omnio 
 **Model:** WS / R101 - PTM210 
 **Production date/period:**  
 **Link to product:** https://www.omnio.ch/de/produkte/wandsender-4-kanal-ws-ch-102.html

**Comment by Jey-Cee** [comment]
In next version

**Comment by Funbug83** [comment]
Hallo Jey-Cee, ich konnte die 4fach Wandschalter auf ENOCEAN_GMBH Produkt PTM210 / PTM 215 anlernen. Somit hat sich für mich dieser Eintrag erledigt :-)
