### ISSUE TITLE
Eltako FKS-SV

### ISSUE THREAD

**Issue by ioBroker-User** [Jey-Cee/ioBroker.enocean#88]
**Manufacturer:** Eltako 
 **Model:** FKS-SV 
 **Production date/period:**  
 **Link to product:** https://www.eltako.de/product/professional-smart-home/fensterkontakte-temperatursensoren-temperaturregler-bewegungs-helligkeitssensoren-und-sonstige-sensoren/fks-sv/ 
 Guten Tag, der Stellantrieb FKS-SV ist wohl ein Smart Valve von MinebeaMitsumi. Der Stellantrieb arbeitet nach dem Protokoll EEP A5-20-01. 
https://www.minebeamitsumi.eu/smartvalve/
https://www.minebeamitsumi.eu/fileadmin/minebeamitsumi.net/Landingpages/02_SmartValve/datasheet_SmartValve.pdf
Ich hatte versucht über die Kieback und Peter MD15-FTL Stellantriebe den Stellantrieb hinzuzufügen, was im Log mit folgenden einträgen nicht geklappt hat: 

Create objects for NAN-NAN-NAN from PMDM_GMBH with id: <idofEnoceanDevice>
EEP NAN-NAN-NAN unknown, send this information to developer.

**Comment by kernsche** [comment]
Hi, ich habe nun den FKS-SV getestet, allerdings übernimmt der Stellmotor die Einstellungen nicht und blinkt 3 mal, was laut Doku ein Kommunikationsfehler sei.
Hier das Log, wenn der Stellmotor mit dem Controller kommuniziert und dieser dann nach ca. 70 ms entsprechend zurück sendet. 
[enoceanLog FKS-SV.log](https://github.com/Jey-Cee/ioBroker.enocean/files/7341245/enoceanLog.FKS-SV.log)

Hier noch ein Screenshot der Objekte:
![image](https://user-images.githubusercontent.com/24193767/137208979-e5f6c85c-8eec-42fb-8842-b1defa55a3af.png)

Ausfällig ist auch, das nach der Übertragung der Daten vom Stellmotor kurz verschiedene Werte etwas "komisch" angezeigt werden: 
![image](https://user-images.githubusercontent.com/24193767/137209146-4f2db975-8709-439d-9100-e20e6a3de38a.png)

Erneutes Einlernen und das Senden von verschiedenen Werten für CMD, SP, SPN, TMP wurde schon probiert, allerdings hat sich hier nichts verändert. Auch die der Intervall bis zum zurück senden der Daten vom Controller zum Stellmotor wurde schon angepasst (zwischen 10 und 500 ms).

**Comment by Jey-Cee** [comment]
Also anhand deines Logs kann ich nur sagen das die Komischen Werte Zustande kommen weil der FKS-SV ein Lerntelegram sendet. Vermutlich weil du die Taste am Gerät gedrückt hast.
Dann fällt mir auf das der FKS noch einen anderen Telegramtyp sendet, als der der angegeben ist. Hast du ein Raumthermostat oder anderes an dem FKS angelernt? 
Dann wird das wohl vom FKS nochmal gesendet.

Aber warum der FKS behauptet es gibt ein Kommunikationsproblem kann ich nicht sehen, das Telegramm was von ioBroker gesendet wird ist korrekt.

**Comment by kernsche** [comment]
Leider war ich die letzte Zeit viel beschäftigt, weshalb ich jetzt erst dazu kam. mich zu melden!

Ich habe nun nochmal ein wenig rum probiert, und kann das nachvollziehen was du sagst und habe das nun mal tiefer analysiert. Mein Denkfehler zu dem vorherigen Post habe ich jetzt gesehen. 
Allerdings stellt sich der FKS immernoch nicht auf meine gewünschte Position ein, sondern bleibt meist bei 50% stehen. Nach 2-3 Tagen "laufen" lassen stellt er manchmal irgendwas ein, was mich auch sehr wundert.
In einigen Beispielen zu dem entsprechenden EEP A5-20-01(http://tools.enocean-alliance.org/EEPViewer/profiles/A5/20/01/A5-20-01.pdf) habe ich gesehen, dass hier auch die Raumtemperatur übergeben wird, obwohl der Stellantrieb auf "Ventilpositionsmodus" steht: 
![image](https://user-images.githubusercontent.com/24193767/138956537-f79bf1e8-63f3-40d5-bac0-5f74199ec601.png)

Setze ich nun ein paar Werte oder auch den "Point Inverse" ändert sich im Bezug auf diese Werte nichts in der entsprechende Ausgabe zum Stellantrieb: 

![image](https://user-images.githubusercontent.com/24193767/138956496-163f71f8-1e3b-4aa8-a570-40e659d0e435.png)

![image](https://user-images.githubusercontent.com/24193767/138956618-fe8a24ae-b623-42cc-b902-3e61010b9c56.png)


Ich gehe davon aus, dass im gesamte String 55000a0701eba564000008ffc7a98d0000059576b0ff00ad der Teil 64000008 die entsprechenden HEX-Data-Werte für EEP A5-20-01 sein sollen. Wenn ich das jetzt "aufsplitte", dann kommt folgendes raus
Hex 6        4       0       0      0        0       0       8
Bin  0110 0100 0000 0000 0000 0000 0000 1000

0x64 wären Dezimal 100=100% was ja erstmal passt. Die nächsten 2 HEX-Werte müssten allerdings die Raumtemperatur sein, wobei hier einfach "0x00" geschickt wird. Wenn ich mich nicht verrechnet habe müsste bei 25°C Raumtemperatur allerdings DEC 95 also 0x5F an der Stelle stehen( 255 - 255 x Raumtemp / 40 = DEC ; 255 - 255 x 25 / 40 = 95,625 => 95 => 0x5F). Da ich ja auch den Point Inverse gesetzt habe müsste sich die nächsten 2 Hex-Werte auf 0x02 setzen.  Die letzten zwei HEX-Werte passen dann wieder. Somit würden folgende HEX/BIN-Werte für den FKS rauskommen: 

HEX 6       4       7       2        0       2      0       8
BIN 0110 0100  0111 0010 0000 0010 0000 1000

Hab ich was übersehen? Ich sehe der FKS schickt danach ein "OK", allerdings stellt er einfach nicht auf die hier angegeben 100 Prozent ein, sondern bleibt bei 50% stehen, weshalb ich hier die Vermutung habe, dass man Ihm trotzdem eine Raumtemperatur mitgeben muss.
Generell wäre es ganz praktisch, wenn man noch die anderen Werte, wie Summer Bit oder die Service Funktionen nutzen kann, die im EEP beschrieben sind (http://tools.enocean-alliance.org/EEPViewer/profiles/A5/20/01/A5-20-01.pdf).

Danke für die Mühe!

**Comment by Jey-Cee** [comment]
Besteht das Problem noch?
Setpoint inverse konnte nicht funktionieren, da wurde irgendein zufälliger Wert gesendet.
