### ISSUE TITLE
ADD Eltako FAH Aussen-Helligkeitssensor

### ISSUE THREAD

**Issue by mustangix** [Jey-Cee/ioBroker.enocean#90]
**Manufacturer**: Eltako
**Model**: FAH
**Production date/period**: nicht angegeben
**Link to product**: https://www.eltako.com/fileadmin/downloads/de/_bedienung/FAH_30000455-2_internet_dtsch.pdf

Lerntelegram:
enocean.0	2021-10-06 12:42:34.530	debug	Message for ID 000321f5 has been received. It was repeated 0 times.
enocean.0	2021-10-06 12:42:34.528	debug	55000a0701eba518080382000321f50000ffffffff3700

Zur Zeit als FAH65S eingebunden - Werte werden erkannt und scheinen momentan plausibel.

e801000a entspricht dem kleinsten Wert von 300lx.
e8ff000a entspricht dem höchsten Wert von 30.000lx

Gruß mustang

**Comment by Jey-Cee** [comment]
Hab es gerade eingebaut. Kannst du mal checken ob das so passt.

**Comment by mustangix** [comment]
...war ich zu schnell - hab gerade von github neu installiert, sehe aber den FAH noch nicht?

**Comment by Jey-Cee** [comment]
Nein warst nicht zu schnell, der wurde beim upload wieder entfernt.
Ich lad das später nochmal hoch.

**Comment by Jey-Cee** [comment]
So jetzt ist es auch auf Github drin.

**Comment by mustangix** [comment]
Anlernen funktioniert einwandfrei, jedoch ist kein Helligkeitswert "ILL" abgebildet sondern "SVC" = "Supply Voltage 0...5.1V".

**Comment by mustangix** [comment]
..übrigens erhalte ich mit dieser neuen Version plötzlich Logmeldungen wie folgt (alle Rollladenaktoren, hier nur ein Beispiel):

enocean.0 | 2021-10-06 18:40:08.112 | warn | State "enocean.0.05937ce2.AIB0" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
enocean.0 | 2021-10-06 18:40:08.109 | warn | State "enocean.0.05937ce2.A0BI" has no existing object, this might lead to an error in future versions
enocean.0 | 2021-10-06 18:40:08.063 | warn | State "enocean.0.05937ce2.AIBI" has no existing object, this might lead to an error in future versions
enocean.0 | 2021-10-06 18:40:08.045 | warn | State "enocean.0.05937ce2.A0B0" has no existing object, this might lead to an error in future versions

**Comment by Jey-Cee** [comment]
Ah die Log Meldungen kannst du erstmal ignorieren. 

Warum der ILL nicht angelegt wird versteh ich nicht. SVC ist gewollt da.
Hast du versucht den FAH erneut an zu legen?

**Comment by mustangix** [comment]
Ja, neu angelegt hatte ich schon mit dem selben Ergebnis. Müßte der Sensor nicht im Prinzip das gleiche Profil, wie der FAH65S haben? - ist auch ohne Batterie und SVC ist nicht vorhanden.

**Comment by Jey-Cee** [comment]
OK hab den Fehler gefunden. Die Definition für das Objekt ILL hat gefehlt.

Fix ist schon auf Github.

**Comment by mustangix** [comment]
Funktioniert - vielen Dank. Vielleicht beim nächsten Update noch den Schritt-für-Schritt-Text anpassen, da jetzt ja die ID eingetragen werden muß und nicht über den LRN-Button installiert wird.

**Comment by Jey-Cee** [comment]
Danke für den Hinweis, das hatte ich nur zum Testen geändert. Das ändere ich wieder auf den ursprung zurück.

**Comment by mustangix** [comment]
hallo, sorry, da ist mir ein Fehler unterlaufen: der niedrigste Wert ist
e800000a
Mir ist aufgefallen, daß er jetzt ca. 183lx als niedrigsten Wert anzeigt, und das kann ja nicht sein.
Magst Du das bitte beim nächsten Update mit einfliessen lassen, momentan kann ich auch so damit leben.
Vielen Dank. Gruß mustang

**Comment by Jey-Cee** [comment]
Sicher das er im FAH65S die Richtigen Werte angezeigt hat?
Bei beiden wird die selbe Formel zur Umrechnung der Werte verwendet, dann müsste es auch bei beiden falsch sein.

**Comment by mustangix** [comment]
der FAH65S hat einen Bereich von 0 bis 30000lx und der ist momentan auf 0lx. Der FAH zeigt momentan 183lx bei einem Bereich von 300 bis 30000lx an.

**Comment by Jey-Cee** [comment]
> der FAH65S hat einen Bereich von 0 bis 30000lx

Laut Telegramm Beschreibung von Eltako hat er 0-100lx und 300-30000lx. Das heist dazwischen ist ein Bereich der Undefiniert ist und potentiell 0 ist.
Somit ist es Wahrscheinlich das die Berechnung auch beim FAH65S falsch ist.

![image](https://user-images.githubusercontent.com/16007760/136837358-cbc0f609-a2e8-49a1-a870-05935c32c5a8.png)

**Comment by mustangix** [comment]
das ist wohl leider wahr - ich hatte nur schnell in der Anleitung zum FAH65S geschaut und nicht in Telegrammbeschreibung :-(

**Comment by mustangix** [comment]
..zum FAH65S hatten wir seinerzeit schon mal geschrieben, auch wegen der Anzeige 0-100 und 300-30000.

**Comment by Jey-Cee** [comment]
Ich hab die Berechnung jetzt für beide angepasst. Bitte mal Testen.

**Comment by mustangix** [comment]
Moin - beim FAH wird es in dieser Version Data_byte2 = x00 entsprechend 300lx und x01 dann ~416lx richtig angezeigt - der fängt ja auch mit 300lx Data_byte2 = x00 an.

Wenn das beim FAH65S genauso sein soll Data_byte2 = x00=300lx, dürfen die 300 Lux nur im undefinierten Bereich von Data_byte3 = x65 bis xFF angezeigt werden und darunter entsprechend die Dämmerungswerte von Data_byte3 = x00 bis x64.
Die 300lx werden sonst nie zur Anzeige gebracht.

Das ist nach meinem jetzigen Verständnis glaube ich richtig, aber verdammt kompliziert.
