### ISSUE TITLE
Eltako FJ62NP-230V

### ISSUE THREAD

**Issue by Micha2536** [Jey-Cee/ioBroker.enocean#92]
Ist es möglich einen Datenpunkt für die RT anzulegen der nicht vom Aktor selber überschrieben werden kann.
Somit kann man festlegen wie lang die Laufzeit sein soll. Damit lässt sich besser arbeiten, da nur ein Wert getigert werden muss.
Aktuell wird beim händischen bedienen ein Wert von 10tel Sekunden angezeigt und daher kann nicht einfach nur der Befehl zum runter oder rauf fahren gesendet werden.
Aktor fährt 80 Sekunden - Ausgabe bei RT dann 800

Oder die Begrenzung des Datenpunktes aufheben so das der letzte RT Wert genutzt wird.

Vielen Dank

**Comment by Jey-Cee** [comment]
Welche Version vom Adapter verwendest du?
Was meinst du mit "die Begrenzung des Datenpunkts aufheben so das der letzte RT Wert genutzt wird"?

**Comment by Jey-Cee** [comment]
In version 0.8.3
